### ISSUE TITLE
Error when running db migration rake task.

### ISSUE THREAD

**Issue by amalfra** [peatio/peatio#393]
Im getting following error when running db migrations:

rake aborted!
Psych::SyntaxError: (<unknown>): could not find expected ':' while scanning a simple key at line 22 column 3
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/figaro-0.7.0/lib/figaro.rb:21:in `raw'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/figaro-0.7.0/lib/figaro.rb:17:in `env'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/figaro-0.7.0/lib/figaro/railtie.rb:7:in `block in <class:Railtie>'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:36:in `call'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:44:in `each'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/railties-4.0.12/lib/rails/application.rb:67:in `inherited'
/home/deploy/peatio/current/config/application.rb:15:in `<module:Peatio>'
/home/deploy/peatio/current/config/application.rb:14:in `<top (required)>'
/home/deploy/peatio/current/Rakefile:5:in `require'
/home/deploy/peatio/current/Rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)

Any idea how to fix this?

**Comment by amalfra** [comment]
Fixed it... was an issue with space in yml
