### ISSUE TITLE
Matching daemon unexpectedly crashes

### ISSUE THREAD

**Issue by brossi** [peatio/peatio#442]
*Note: these experiences are occuring on an internal test exchange intended for development of a different product so no real funds are at risk.*

ENV=Production

I'm having a hard time tracking this crash back to the data condition that is generating it. When I start the daemons using `bundle exec rake daemons:start` all but 'match.rb' initialize as expected. The daemon that crashes produces this stack trace:

```
/home/deploy/peatio/current/app/models/worker/matching.rb:33:in `submit': undefined method `submit' for nil:NilClass (NoMethodError)
        from /home/deploy/peatio/current/app/models/worker/matching.rb:74:in `block in load_orders'
        from /home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.12/lib/active_record/relation/delegation.rb:13:in `each'
        from /home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.12/lib/active_record/relation/delegation.rb:13:in `each'
        from /home/deploy/peatio/current/app/models/worker/matching.rb:73:in `load_orders'
        from /home/deploy/peatio/current/app/models/worker/matching.rb:64:in `initialize_engine'
        from /home/deploy/peatio/current/app/models/worker/matching.rb:42:in `block in reload'
        from /home/deploy/peatio/current/app/models/worker/matching.rb:42:in `each'
        from /home/deploy/peatio/current/app/models/worker/matching.rb:42:in `reload'
        from /home/deploy/peatio/current/app/models/worker/matching.rb:14:in `initialize'
        from /home/deploy/peatio/current/app/models/amqp_config.rb:25:in `new'
        from /home/deploy/peatio/current/app/models/amqp_config.rb:25:in `binding_worker'
        from /home/deploy/peatio/current/lib/daemons/amqp_daemon.rb:36:in `block in <top (required)>'
        from /home/deploy/peatio/current/lib/daemons/amqp_daemon.rb:35:in `each'
        from /home/deploy/peatio/current/lib/daemons/amqp_daemon.rb:35:in `<top (required)>'
        from /home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
        from /home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
        from /home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
        from /home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
        from /home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
        from /home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
        from /home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
        from /home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
        from /home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
        from lib/daemons/matching_ctl:11:in `<main>'
```
It works as expected locally which tells me it's most likely a problem with an order that was placed on the "public" system.

I looked in the referenced files but didn't see anything obvious that pointed to why this daemon was crashing (and only on a certain market). Are there any suggestions for data conditions that I should check the DB for, or other options for digging into this problem at a deeper level?

**Comment by brossi** [comment]
Error was on my end. I had a duplicated currency ID in `markets.yml`. Closing the issue as "not a problem with Peatio, problem existed between keyboard and chair".

**Comment by GH0STL1N3R** [comment]
Thanks, this actually helped me solve the matching issue I had. Had also duplicate currency ID
