### ISSUE TITLE
Possible problem With Ruby Version & Readline

### ISSUE THREAD

**Issue by Gensia** [peatio/peatio#456]
In following the instructions to deploy the Production server on ubuntu-14.04.2-server-amd64 I encounter this problem at "bundle exec rake db:setup" command. This has worked for me before so I think this is a problem not with Peatio itself. 

I have a working development version can someone tell me if its okay to use this as a Production server and if not why not.

~/peatio/current$ bundle exec rake db:setup --trace
** Invoke db:setup (first_time)
** Invoke db:schema:load_if_ruby (first_time)
** Invoke db:create (first_time)
** Invoke db:load_config (first_time)
** Execute db:load_config
** Execute db:create
peatio_production already exists
** Invoke environment (first_time)
** Execute environment
====================== WARNING ======================
  please check below config in config/application.yml

  PUSHER_APP
  PUSHER_KEY
  PUSHER_SECRET
=====================================================
rake aborted!
config missing
/home/deploy/peatio/current/config/initializers/check_env.rb:17:in `<top (required)>'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:223:in `load'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:223:in `block in load'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:214:in `load_dependency'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:223:in `load'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/engine.rb:609:in `block (2 levels) in <class:Engine>'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/engine.rb:608:in `each'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/engine.rb:608:in `block in <class:Engine>'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/initializable.rb:30:in `instance_exec'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/initializable.rb:30:in `run'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:420:in `block (2 levels) in each_strongly_connected_component_from'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:419:in `block in each_strongly_connected_component_from'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/initializable.rb:44:in `each'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/initializable.rb:44:in `tsort_each_child'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:413:in `call'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:413:in `each_strongly_connected_component_from'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `each'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `call'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/initializable.rb:54:in `run_initializers'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/application.rb:215:in `initialize!'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/railtie/configurable.rb:30:in `method_missing'
/home/deploy/peatio/current/config/environment.rb:5:in `<top (required)>'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:229:in `require'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:229:in `block in require'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:214:in `load_dependency'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:229:in `require'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/application.rb:189:in `require_environment!'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/application.rb:260:in `block in run_tasks_blocks'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:201:in `block in invoke_prerequisites'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:199:in `each'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:199:in `invoke_prerequisites'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:178:in `block in invoke_with_call_chain'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:201:in `block in invoke_prerequisites'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:199:in `each'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:199:in `invoke_prerequisites'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:178:in `block in invoke_with_call_chain'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/home/deploy/.rbenv/versions/2.2.1/bin/rake:33:in `<main>'
Tasks: TOP => db:setup => db:schema:load_if_ruby => environment

**Comment by Gensia** [comment]
Problem was with application.yml

I entered Pusher settings into 

PUSHER_APP: YOUR_PUSHER_APP
PUSHER_KEY: YOUR_PUSHER_KEY
PUSHER_SECRET: YOUR_PUSHER_SECRET

Now "bundle exec rake db:setup" works

This was perhaps a careless mistake but I leave it up as someone may have same problem.
