### ISSUE TITLE
My app crashes with a “You can't use Gon public methods for storing data” error

### ISSUE THREAD

**Issue by tkembo** [peatio/peatio#466]
I keep getting the following error:

```
Completed 500 Internal Server Error in 9ms
F, [2015-08-11T13:32:09.513613 #10107] FATAL -- : 
RuntimeError (You can't use Gon public methods for storing data):
app/controllers/application_controller.rb:204:in `set_gon'
lib/middleware/security.rb:11:in `call'
```

The following file is the one which is said to have the error: [https://github.com/peatio/peatio/blob/master/app/controllers/application_controller.rb](https://github.com/peatio/peatio/blob/master/app/controllers/application_controller.rb)

Line 204 is mentioned in the error. If it helps, here is what line 203 to line 213 looks like:
```
if current_user
      gon.current_user = { sn: current_user.sn }
      gon.accounts = current_user.accounts.inject({}) do |memo, account|
        memo[account.currency] = {
          currency: account.currency,
          balance: account.balance,
          locked: account.locked
        } if account.currency_obj.try(:visible)
        memo
      end
    end
```

The problem is either with the Gon gem or with the code. Any idea how i could resolve this?

**Comment by hpyhacking** [comment]
bug fixed?

**Comment by tkembo** [comment]
Yes. Problem was that we were using a reserved word  ```env``` when we used ```gon.env``` and so I fixed it by changing ```gon.env``` to ```gon.enviro``` in ```app/controllers/application_controller.rb```

**Comment by raisty** [comment]
Still facing issue. enviro cannot solve issue

**Comment by liushmh** [comment]
same issue, anyone knows how to fix?

**Comment by onlyyouandty** [comment]
The issue is with the version of `Gon` in either the `Gemfile` or `Gemfile.lock`.

1. Make sure the `Gemfile` has `gem 'gon', '~> 5.2.0'`
2. After `bundle install`, check the `Gemfile.lock` to make sure `gon (5.2.0)` is what is locked down there and not `gon (5.2.3)`. If it is anything other than `gon (5.2.0)`, manually change it to `gon (5.2.0)` in the Gemfile.lock and bundle install again and make sure you still have `gon (5.2.0)`. 

This solves it for me whenever the problem appears.
