### ISSUE TITLE
Images Don't Appear in Production Server

### ISSUE THREAD

**Issue by Gensia** [peatio/peatio#474]
And yet they do in the development server. Can the development server be used in place of the Production server given the Production server is non functional?

**Comment by hpyhacking** [comment]
r u sure run assets:precompile in production server?

**Comment by Gensia** [comment]
Yes still no images

**Comment by tkembo** [comment]
Try cleaning your assets and then running `assets:precompile` again. Use these commands

1. `$ bundle exec rake assets:clean`
2. `$ bundle exec rake assets:clobber`
3. `$ bundle exec rake assets:precompile`

**Comment by LoRdMiCk** [comment]
got the same here..

**Comment by tkembo** [comment]
Can you give more details? which images can't you see exactly, where are they located and on where on the site?

**Comment by LoRdMiCk** [comment]
on my side I got that

![image](https://cloud.githubusercontent.com/assets/5883336/10300342/20129edc-6bc3-11e5-90f6-43a388d8879d.png)

**Comment by LoRdMiCk** [comment]
I delete the public folder as a test and it doesnt made any difference.. so its like it wasnt there 
like the path is wrong somewhere..

**Comment by tkembo** [comment]
Wait! DONT DELETE THE PUBLIC FOLDER!

Try putting your images in the public folder. Let's say your image is in the path `/public/logo.png`, you can access the image from your code with: `<img src='/logo.png' />`

Putting your images in the public folder is the easy workaround

**Comment by Gensia** [comment]
Still same, no images and broken layout. These problems do not exist in the development version so is it possible to use the development version in place of the production server? If so how to get the development version to send emails?

**Comment by LoRdMiCk** [comment]
when I look the image info in the browser it say the image is there... http://192.168.1.147:3000/assets/logo-16fe7c97fc77dc932c33d318b990eb0d.png

**Comment by valuead** [comment]
You are on the private IP address

**Comment by LoRdMiCk** [comment]
thats the link to one of the image who doesnt work..

**Comment by LoRdMiCk** [comment]
deploy@exchange:~/peatio/current$ bundle exec rails server
=> Booting WEBrick
=> Rails 4.0.12 application starting in production on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
[2015-10-06 10:52:35] INFO  WEBrick 1.3.1
[2015-10-06 10:52:35] INFO  ruby 2.2.1 (2015-02-26) [x86_64-linux]
[2015-10-06 10:52:35] INFO  WEBrick::HTTPServer#start: pid=21083 port=3000
I, [2015-10-06T10:52:51.965580 #21083]  INFO -- : Started GET "/" for 174.92.224.39 at 2015-10-06 10:52:51 -0400
I, [2015-10-06T10:52:52.036616 #21083]  INFO -- : Processing by WelcomeController#index as HTML
I, [2015-10-06T10:52:52.130349 #21083]  INFO -- :   Rendered welcome/index.html.slim within layouts/landing (31.5ms)
I, [2015-10-06T10:52:52.144841 #21083]  INFO -- :   Rendered shared/_html5.html.slim (3.0ms)
I, [2015-10-06T10:52:52.151918 #21083]  INFO -- :   Rendered shared/_meta.html.slim (5.8ms)
I, [2015-10-06T10:52:52.162284 #21083]  INFO -- :   Rendered shared/_alert.html.slim (8.3ms)
I, [2015-10-06T10:52:52.190863 #21083]  INFO -- :   Rendered shared/_footer.html.slim (12.0ms)
I, [2015-10-06T10:52:52.191907 #21083]  INFO -- : Completed 200 OK in 155ms (Views: 95.5ms | ActiveRecord: 15.0ms)
I, [2015-10-06T10:52:52.391967 #21083]  INFO -- : Started GET "/assets/application-00faa91f212698c016e6fce10b896f2c.css" for 174.92.224.39 at 2015-10-06 10:52:52 -0400
F, [2015-10-06T10:52:52.397258 #21083] FATAL -- :
ActionController::RoutingError (No route matches [GET] "/assets/application-00faa91f212698c016e6fce10b896f2c.css"):
  lib/middleware/security.rb:11:in `call'


I, [2015-10-06T10:52:52.401392 #21083]  INFO -- : Started GET "/assets/application-89b9c8d2652301fa3c8f31f8e97d0d1f.js" for 174.92.224.39 at 2015-10-06 10:52:52 -0400
F, [2015-10-06T10:52:52.409118 #21083] FATAL -- :
ActionController::RoutingError (No route matches [GET] "/assets/application-89b9c8d2652301fa3c8f31f8e97d0d1f.js"):
  lib/middleware/security.rb:11:in `call'


I, [2015-10-06T10:52:52.419207 #21083]  INFO -- : Started GET "/assets/locales/en-d19968f9c0857d554ab5eece41d02f79.js" for 174.92.224.39 at 2015-10-06 10:52:52 -0400
F, [2015-10-06T10:52:52.425147 #21083] FATAL -- :
ActionController::RoutingError (No route matches [GET] "/assets/locales/en-d19968f9c0857d554ab5eece41d02f79.js"):
  lib/middleware/security.rb:11:in `call'


I, [2015-10-06T10:52:52.428557 #21083]  INFO -- : Started GET "/assets/logo-16fe7c97fc77dc932c33d318b990eb0d.png" for 174.92.224.39 at 2015-10-06 10:52:52 -0400
F, [2015-10-06T10:52:52.433366 #21083] FATAL -- :
ActionController::RoutingError (No route matches [GET] "/assets/logo-16fe7c97fc77dc932c33d318b990eb0d.png"):
  lib/middleware/security.rb:11:in `call'

**Comment by LoRdMiCk** [comment]
ok.. I temporary fix it.. 

1- I send the folder "public" on another web server.. 
2- nano config/environments/production.rb
3- I uncomment line 61 and change it to fix the server where public it hosted..

now it work but I would prefer to have it work the right way..

**Comment by Gensia** [comment]
I got same output. 
These webpages have pointers for getting email to work on a development server
http://stackoverflow.com/questions/4313177/sending-mail-with-rails-3-in-development-environment
http://andr.esmejia.com/posts/20-send-real-mail-with-rails-from-your-development-environment-on-mac-os-x

SSL would be important also not yet looked into that.

**Comment by Gensia** [comment]
This is now a project on Freelancer if anyone is up to the job.....?
https://www.freelancer.com/projects/email-handling/Make-Peatio-Development-Version-Send/#/details
Project ID: 8667926

**Comment by eCurrency** [comment]
Gensia,

I was thinking of doing the same thing, then decided to pay another developer for a seriously secure, fully functioning system with independence, on-going development.

I'm concerned about the security and on-going support support of peatio at this point, but if we can find someone to take this journey with is I'm willing to do a partnership on the costs and the results.

We split the costs and and both have access to the results?

Let me know.

**Comment by Gensia** [comment]
After I have these two problems sorted I will be able to make a secure Peatio exchange hopefully. There is always issues though I would have got in contact with you earlier because I thought I would have it running buy now. Here's my email: chris.windram@yandex.com

**Comment by saravanan95** [comment]
Add these two lines in **/config/environments/production.rb**
config.assets.compile = true
config.assets.precompile =  ['*.js', '*.css', '*.css.erb'] 

and run this command
RAILS_ENV=production bundle exec rake assets:precompile

**Comment by nomgbr** [comment]
I had the same problem and fixed the assets routing with  the solution of @saravanan95
but now I have the same problem with : languages, sounds and templates (in the public folder)
what am i missing here ?, Is there a way to compile these files as well?
thanks
