### ISSUE TITLE
error in setup bundle exec rake db:setup

### ISSUE THREAD

**Issue by abhijeetjaswal** [peatio/peatio#481]
tried couple of time with fresh installs but not able to move ahead. error trace is 

rake aborted!
Psych::SyntaxError: (<unknown>): did not find expected key while parsing a block mapping at line 6 column 3
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/psych.rb:370:in `parse'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/psych.rb:370:in `parse_stream'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/psych.rb:318:in `parse'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/psych.rb:245:in `load'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/figaro-0.7.0/lib/figaro.rb:21:in `raw'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/figaro-0.7.0/lib/figaro.rb:17:in `env'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/figaro-0.7.0/lib/figaro/railtie.rb:7:in `block in <class:Railtie>'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:36:in `call'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:44:in `each'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.0.12/lib/rails/application.rb:67:in `inherited'
/home/ubuntu/peatio/config/application.rb:15:in `<module:Peatio>'
/home/ubuntu/peatio/config/application.rb:14:in `<top (required)>'
/home/ubuntu/peatio/Rakefile:5:in `require'
/home/ubuntu/peatio/Rakefile:5:in `<top (required)>'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load_rakefile'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:689:in `raw_load_rakefile'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:94:in `block in load_rakefile'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:93:in `load_rakefile'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:77:in `block in run'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/home/ubuntu/.rbenv/versions/2.2.1/bin/rake:33:in `<main>'

**Comment by abhijeetjaswal** [comment]
help please.. i am stuck here!!

**Comment by ShadowMyst** [comment]
Check out the spaces in Pusher's part in config / aplication.yml
That problem I also had and it was to have spaces of more
