### ISSUE TITLE
Configuring Peatio exchange, Rake aborted

### ISSUE THREAD

**Issue by Darkhashuk** [peatio/peatio#487]
Hi im trying to install peatio exchange in ubuntu 12.04 LTS but when i try to deploy Bundle exec rake, they abort the instalation here is the report with the flag --trace,

thanks for all the Help.

N3rvi0zz0 Btctalk

arkhash@Darkhash:/usr/local/peatio$ bundle exec rake daemons:start --trace
rake aborted!
Psych::SyntaxError: (<unknown>): did not find expected key while parsing a block mapping at line 6 column 3
/home/darkhash/.rbenv/versions/2.2.1/lib/ruby/2.2.0/psych.rb:370:in `parse'
/home/darkhash/.rbenv/versions/2.2.1/lib/ruby/2.2.0/psych.rb:370:in `parse_stream'
/home/darkhash/.rbenv/versions/2.2.1/lib/ruby/2.2.0/psych.rb:318:in `parse'
/home/darkhash/.rbenv/versions/2.2.1/lib/ruby/2.2.0/psych.rb:245:in `load'
/home/darkhash/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/figaro-0.7.0/lib/figaro.rb:21:in `raw'
/home/darkhash/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/figaro-0.7.0/lib/figaro.rb:17:in `env'
/home/darkhash/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/figaro-0.7.0/lib/figaro/railtie.rb:7:in `block in <class:Railtie>'
/home/darkhash/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:36:in `call'
/home/darkhash/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
/home/darkhash/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
/home/darkhash/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:44:in `each'
/home/darkhash/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
/home/darkhash/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.0.12/lib/rails/application.rb:67:in `inherited'
/usr/local/peatio/config/application.rb:15:in `<module:Peatio>'
/usr/local/peatio/config/application.rb:14:in `<top (required)>'
/usr/local/peatio/Rakefile:5:in `require'
/usr/local/peatio/Rakefile:5:in `<top (required)>'
/home/darkhash/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load'
/home/darkhash/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load_rakefile'
/home/darkhash/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:689:in `raw_load_rakefile'
/home/darkhash/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:94:in `block in load_rakefile'
/home/darkhash/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/home/darkhash/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:93:in `load_rakefile'
/home/darkhash/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:77:in `block in run'
/home/darkhash/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/home/darkhash/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/home/darkhash/.rbenv/versions/2.2.1/bin/rake:33:in `<main>'
darkhash@Darkhash:/usr/local/peatio$

**Comment by tkembo** [comment]
What's the output when you run the command without the --trace?

**Comment by ychaim** [comment]
tkembo, did you manage to update the price?  my still 0.0  :-(

**Comment by Darkhashmaster** [comment]
Hi and sorry I need to open another account, yesterday somebody still my laptop on the tube.

The comand  bundle exec rake daemons:start  without trace give me this output.

darkhash@Darkhash:/usr/local/peatio$ bundle exec rake daemons:start
rake aborted!
Psych::SyntaxError: (<unknown>): did not find expected key while parsing a block mapping at line 6 column 3
/usr/local/peatio/config/application.rb:15:in `<module:Peatio>'
/usr/local/peatio/config/application.rb:14:in `<top (required)>'
/usr/local/peatio/Rakefile:5:in `require'
/usr/local/peatio/Rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)
darkhash@Darkhash:/usr/local/peatio$ 



maybe i need to modify any yml appart from application and currencies?


Maybe because the blockchain didnt finish to sync?

as you see in the output I installed peatio in /usr/local/peatio not in /usr/local/share/peatio maybe Gems are looking in the wrong folder.


Thanks a lot in advance

**Comment by mufeedk** [comment]
Hi Darkhashmaster,
 Have you solved this issue ?. I got same error when run bundle exec rake db:setup
Thanks

**Comment by insiderq** [comment]
Hi guys, i've figured out what's happening here. This errors are all about errors in parsing config files.
Take a close look at them and be aware that indentaions(spaces) matters!
