### ISSUE TITLE
Access admin panel error

### ISSUE THREAD

**Issue by eddef** [peatio/peatio#501]
When trying to access the admin panel it comes up with this error. Anybody have a clue?

`I, [2016-03-01T16:26:08.087118 #1140]  INFO -- : Processing by Admin::DashboardController#index as HTML
I, [2016-03-01T16:26:08.097891 #1140]  INFO -- :   Rendered admin/dashboard/index.html.slim within layouts/admin (0.6ms)
I, [2016-03-01T16:26:08.098047 #1140]  INFO -- : Completed 500 Internal Server Error in 11ms
F, [2016-03-01T16:26:08.099246 #1140] FATAL -- :
ActionView::Template::Error (String can't be coerced into BigDecimal):
    25:                   - if c[:hot] == 'N/A'
    26:                     td.text-right = c[:hot]
    27:                   - else
    28:                     td.text-right = c[:sum] - c[:hot]
    29:                 - else
    30:                   td.text-right N/A
    31:                   td.text-right N/A
  app/views/admin/dashboard/index.html.slim:28:in `-'
  app/views/admin/dashboard/index.html.slim:28:in `block in _app_views_admin_dashboard_index_html_slim__2629484846423445097_69913904902660'
  app/views/admin/dashboard/index.html.slim:16:in `each'
  app/views/admin/dashboard/index.html.slim:16:in `_app_views_admin_dashboard_index_html_slim__2629484846423445097_69913904902660'
  lib/middleware/security.rb:11:in `call'
`

**Comment by hrishikeshio** [comment]
Is bitcoin correctly configured and running? is currency.yml correctly configured?

**Comment by eddef** [comment]
Bitcoind is running ok, I tested with 2 things, one  bitcoin server on another machine and one that runs on the server itself.  Still same error.  Is there some way to log  and see against the rpc what happens? I suspected it was something with this as id had something to do with sums of hot and cold wallets. 

The down side of this is that nothing in the admin panel is accessable.

On the other server another thing raised up, is the correct walletnotify to add -H server_name on the rabbitmqadmin command?

**Comment by hrishikeshio** [comment]
show me your currency.yml and bitcoin.conf

**Comment by eddef** [comment]
bitcoin.conf 
`
server=1
daemon=1
rpcuser=btcadmin
rpcpassword=testing
rpcport=8332
walletnotify=/usr/local/sbin/rabbitmqadmin publish routing_key=peatio.deposit.c$
`
`
 id: 2
  key: satoshi
  code: btc
  symbol: "฿"
  coin: true
  quick_withdraw_max: 0
  rpc: http://btcadmin:testing@127.0.0.1:8332
  blockchain: https://blockchain.info/tx/#{txid}
  address_url: https://blockchain.info/address/#{address}
  assets:
    accounts:
      -
        address: removed
`

**Comment by eddef** [comment]
Hehe, anybody up for hire to help ?

**Comment by eddef** [comment]
After abit more changes and reloding i now have this error.

Showing /home/deploy/peatio/current/app/views/layouts/admin.html.slim where line #35 raised:

undefined method `admin_deposits_satoshis_path' for #<#<Class:0x007f8411b29728>:0x007f84117c0668>

app/views/layouts/admin.html.slim:35:in `block in _app_views_layouts_admin_html_slim___340371537148202449_70102604819260'
app/views/layouts/admin.html.slim:33:in `each'
app/views/layouts/admin.html.slim:33:in `_app_views_layouts_admin_html_slim___340371537148202449_70102604819260'
lib/middleware/security.rb:11:in `call'

I did see a closed issue on this before but no good answer on it.

**Comment by wangyijunjunjun** [comment]
hey , have you solved this problem?

**Comment by awaisraza308** [comment]
what is the directory for admin panel. I am in production mode

**Comment by eddef** [comment]
You need to set yourself as admin user then you will get a extra option in menu for admin.

**Comment by awaisraza308** [comment]
how do i do that?

**Comment by awaisraza308** [comment]
thanks man !!!!!!!!!!!!!!!!!!!!!!!

**Comment by franciscoorte** [comment]
Please... someone to tell me how can I set myself as admin??? I've tried changing database, config files.. but I don't found the key.

Thanks in advance

**Comment by fob71** [comment]
Please... someone to tell me how can I set myself as admin??? I've tried to change database, config files.. but I don't found the key.

@eddef .. please.. help me!!

Thanks in advance

**Comment by awaisraza308** [comment]
Go to peatio > config > application .
Add yourself there.
If it doesn't work let me know.

**Comment by fob71** [comment]
Ohhhh... I changed that email in the config file!!!

Thanks a lot!

**Comment by awaisraza308** [comment]
Awesome no problem if u need anything else let me know.

**Comment by naveen-appoets** [comment]
@fob71 @awaisraza308  Hey, you were able to login to the admin area by simple changing the config/application.yml? What did you do after that? Like how did you give your password? There's only provision to add a mail id right?

anyway after that change, you just restarted the server and you were able to log in with that email using any password?
how does that workk? Kindly let me know.
