### ISSUE TITLE
Phone Verification - Internal Server Error

### ISSUE THREAD

**Issue by wainersec** [peatio/peatio#536]
When trying to set/verify cell-phone number I get the following error:

```
I, [2016-10-03T20:44:53.583544 #16630]  INFO -- : Started PATCH "/verify/sms_auth" for XXX.XXX.XXX.XXX at 2016-10-03 20:44:53 +0000
I, [2016-10-03T20:44:53.584893 #16630]  INFO -- : Processing by Verify::SmsAuthsController#update as JS
I, [2016-10-03T20:44:53.585018 #16630]  INFO -- :   Parameters: {"utf8"=>"✓", "sms_auth"=>{"country"=>"AR", "phone_number"=>"XX XXXX-XXXX", "otp"=>""}, "commit"=>"send_code"}
I, [2016-10-03T20:44:53.677215 #16630]  INFO -- : Completed 500 Internal Server Error in 92ms
F, [2016-10-03T20:44:53.678080 #16630] FATAL -- : 
Errno::ECONNRESET (Connection reset by peer):
  app/models/amqp_queue.rb:6:in `block in connection'
  app/models/amqp_queue.rb:5:in `tap'
  app/models/amqp_queue.rb:5:in `connection'
  app/models/amqp_queue.rb:11:in `channel'
  app/models/amqp_queue.rb:15:in `exchanges'
  app/models/amqp_queue.rb:19:in `exchange'
  app/models/amqp_queue.rb:24:in `publish'
  app/models/amqp_queue.rb:32:in `enqueue'
  app/models/two_factor/sms.rb:30:in `send_otp'
  app/controllers/verify/sms_auths_controller.rb:38:in `block in send_code_phase'
  app/controllers/verify/sms_auths_controller.rb:36:in `send_code_phase'
  app/controllers/verify/sms_auths_controller.rb:14:in `update'
  lib/middleware/security.rb:11:in `call'
```

**Comment by stennyc** [comment]
me too. anybody can help us solve this error?
