### ISSUE TITLE
Psych::SyntaxError: (<unknown>): did not find expected key while parsing a block mapping at line 1 column 1

### ISSUE THREAD

**Issue by dwmcqueen** [peatio/peatio#543]
While running the database set-up, I get this error:

rake aborted!
Psych::SyntaxError: (<unknown>): did not find expected key while parsing a block mapping at line 1 column 1
/home/dwmcqueen/.rbenv/versions/2.2.6/lib/ruby/2.2.0/psych.rb:370:in `parse'
/home/dwmcqueen/.rbenv/versions/2.2.6/lib/ruby/2.2.0/psych.rb:370:in `parse_stream'
/home/dwmcqueen/.rbenv/versions/2.2.6/lib/ruby/2.2.0/psych.rb:318:in `parse'
/home/dwmcqueen/.rbenv/versions/2.2.6/lib/ruby/2.2.0/psych.rb:245:in `load'
/home/dwmcqueen/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/figaro-0.7.0/lib/figaro.rb:21:in `raw'
/home/dwmcqueen/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/figaro-0.7.0/lib/figaro.rb:17:in `env'
/home/dwmcqueen/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/figaro-0.7.0/lib/figaro/railtie.rb:7:in `block in <class:Railtie>'
/home/dwmcqueen/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:36:in `call'
/home/dwmcqueen/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
/home/dwmcqueen/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
/home/dwmcqueen/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:44:in `each'
/home/dwmcqueen/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
/home/dwmcqueen/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/railties-4.0.12/lib/rails/application.rb:67:in `inherited'
/home/dwmcqueen/peatio/config/application.rb:15:in `<module:Peatio>'
/home/dwmcqueen/peatio/config/application.rb:14:in `<top (required)>'
/home/dwmcqueen/peatio/Rakefile:5:in `require'
/home/dwmcqueen/peatio/Rakefile:5:in `<top (required)>'
/home/dwmcqueen/.rbenv/versions/2.2.6/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load'
/home/dwmcqueen/.rbenv/versions/2.2.6/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load_rakefile'
/home/dwmcqueen/.rbenv/versions/2.2.6/lib/ruby/2.2.0/rake/application.rb:689:in `raw_load_rakefile'
/home/dwmcqueen/.rbenv/versions/2.2.6/lib/ruby/2.2.0/rake/application.rb:94:in `block in load_rakefile'
/home/dwmcqueen/.rbenv/versions/2.2.6/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/home/dwmcqueen/.rbenv/versions/2.2.6/lib/ruby/2.2.0/rake/application.rb:93:in `load_rakefile'
/home/dwmcqueen/.rbenv/versions/2.2.6/lib/ruby/2.2.0/rake/application.rb:77:in `block in run'
/home/dwmcqueen/.rbenv/versions/2.2.6/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/home/dwmcqueen/.rbenv/versions/2.2.6/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/home/dwmcqueen/.rbenv/versions/2.2.6/bin/rake:33:in `<top (required)>'
/home/dwmcqueen/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/bundler-1.14.0/lib/bundler/cli/exec.rb:74:in `load'
/home/dwmcqueen/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/bundler-1.14.0/lib/bundler/cli/exec.rb:74:in `kernel_load'
/home/dwmcqueen/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/bundler-1.14.0/lib/bundler/cli/exec.rb:27:in `run'
/home/dwmcqueen/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/bundler-1.14.0/lib/bundler/cli.rb:335:in `exec'
/home/dwmcqueen/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/bundler-1.14.0/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/dwmcqueen/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/bundler-1.14.0/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/dwmcqueen/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/bundler-1.14.0/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/home/dwmcqueen/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/bundler-1.14.0/lib/bundler/cli.rb:20:in `dispatch'
/home/dwmcqueen/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/bundler-1.14.0/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/home/dwmcqueen/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/bundler-1.14.0/lib/bundler/cli.rb:11:in `start'
/home/dwmcqueen/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/bundler-1.14.0/exe/bundle:32:in `block in <top (required)>'
/home/dwmcqueen/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/bundler-1.14.0/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/home/dwmcqueen/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/bundler-1.14.0/exe/bundle:24:in `<top (required)>'
/home/dwmcqueen/.rbenv/versions/2.2.6/bin/bundle:23:in `load'
/home/dwmcqueen/.rbenv/versions/2.2.6/bin/bundle:23:in `<main>'

I had to upgrade the mysql2 gem to be greater than 0.3.17 to deal with the newer version of MySQL.

**Comment by dwmcqueen** [comment]
Duplicate of https://github.com/peatio/peatio/issues/90
