### ISSUE TITLE
NameError: uninitialized constant Deposit::ActiveRecord_Relation

### ISSUE THREAD

**Issue by nlmn2017** [peatio/peatio#544]
Hello 

When I run bundle exec rake db:setup I get below message. Please help on how to proceed. 

Thanks

rake aborted!
NameError: uninitialized constant Deposit::ActiveRecord_Relation
/home/ik/peatio/app/models/concerns/currencible.rb:5:in `block in <module:Currencible>'
/home/ik/peatio/app/models/deposit.rb:8:in `include'
/home/ik/peatio/app/models/deposit.rb:8:in `<class:Deposit>'
/home/ik/peatio/app/models/deposit.rb:1:in `<top (required)>'
/home/ik/peatio/app/observers/transfer_observer.rb:2:in `<class:TransferObserver>'
/home/ik/peatio/app/observers/transfer_observer.rb:1:in `<top (required)>'
/home/ik/peatio/config/environment.rb:5:in `<top (required)>'
/home/ik/.rbenv/versions/2.2.1/bin/bundle:23:in `load'
/home/ik/.rbenv/versions/2.2.1/bin/bundle:23:in `<main>'
Tasks: TOP => db:setup => db:schema:load_if_ruby => environment
(See full trace by running task with --trace)

**Comment by chuanfortune** [comment]
i have same error

**Comment by chuanfortune** [comment]
nlmn2017 have you fixed that issue?
