### ISSUE TITLE
error setting up db 'bundle exec rake db:setup'

### ISSUE THREAD

**Issue by coderwithattitude** [peatio/peatio#545]
Hello while running 'bundle exec rake db:setup'
i get the error below 
please help
Psych::SyntaxError: (<unknown>): did not find expected key while parsing a block mapping at line 6 column 3
/home/bitproject/.rbenv/versions/2.2.1/lib/ruby/2.2.0/psych.rb:370:in `parse'
/home/bitproject/.rbenv/versions/2.2.1/lib/ruby/2.2.0/psych.rb:370:in `parse_stream'
/home/bitproject/.rbenv/versions/2.2.1/lib/ruby/2.2.0/psych.rb:318:in `parse'
/home/bitproject/.rbenv/versions/2.2.1/lib/ruby/2.2.0/psych.rb:245:in `load'
/home/bitproject/peatio/current/vendor/bundle/ruby/2.2.0/gems/figaro-0.7.0/lib/figaro.rb:21:in `raw'
/home/bitproject/peatio/current/vendor/bundle/ruby/2.2.0/gems/figaro-0.7.0/lib/figaro.rb:17:in `env'
/home/bitproject/peatio/current/vendor/bundle/ruby/2.2.0/gems/figaro-0.7.0/lib/figaro/railtie.rb:7:in `block in <class:Railtie>'
/home/bitproject/peatio/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:36:in `call'
/home/bitproject/peatio/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
/home/bitproject/peatio/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
/home/bitproject/peatio/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:44:in `each'
/home/bitproject/peatio/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
/home/bitproject/peatio/current/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/application.rb:67:in `inherited'
/home/bitproject/peatio/current/config/application.rb:15:in `<module:Peatio>'
/home/bitproject/peatio/current/config/application.rb:14:in `<top (required)>'
/home/bitproject/peatio/current/Rakefile:5:in `require'
/home/bitproject/peatio/current/Rakefile:5:in `<top (required)>'
/home/bitproject/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load'
/home/bitproject/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load_rakefile'
/home/bitproject/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:689:in `raw_load_rakefile'
/home/bitproject/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:94:in `block in load_rakefile'
/home/bitproject/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/home/bitproject/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:93:in `load_rakefile'
/home/bitproject/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:77:in `block in run'
/home/bitproject/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/home/bitproject/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/home/bitproject/.rbenv/versions/2.2.1/bin/rake:33:in `<top (required)>'
/home/bitproject/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.14.3/lib/bundler/cli/exec.rb:74:in `load'
/home/bitproject/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.14.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
/home/bitproject/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.14.3/lib/bundler/cli/exec.rb:27:in `run'
/home/bitproject/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.14.3/lib/bundler/cli.rb:335:in `exec'
/home/bitproject/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.14.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/bitproject/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.14.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/bitproject/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.14.3/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/home/bitproject/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.14.3/lib/bundler/cli.rb:20:in `dispatch'
/home/bitproject/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.14.3/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/home/bitproject/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.14.3/lib/bundler/cli.rb:11:in `start'
/home/bitproject/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.14.3/exe/bundle:32:in `block in <top (required)>'
/home/bitproject/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.14.3/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/home/bitproject/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.14.3/exe/bundle:24:in `<top (required)>'
/home/bitproject/.rbenv/versions/2.2.1/bin/bundle:23:in `load'
/home/bitproject/.rbenv/versions/2.2.1/bin/bundle:23:in `<main>'

**Comment by awaisraza308** [comment]
https://bitcointalk.org/index.php?topic=1795210.0

**Comment by outbackdingo** [comment]
why does this sound like a scam to me.... be careful..... who would pay for
code thats already OPEN SOURCE
and if you claim to have "fixed it" why dont you just submit those patches
back to the project ?

**Comment by awaisraza308** [comment]
Please read the entire thread.

**Comment by outbackdingo** [comment]
I did read it.... still smells like a scam

**Comment by zubi94** [comment]
hey im getting this error to did you figure it out?

**Comment by scatterp** [comment]
zubi see scatterp/peatio you need to install an older version of mysql
