### ISSUE TITLE
Why my withdrawal is in "Accepted" state all the time?

### ISSUE THREAD

**Issue by vetal20600** [peatio/peatio#554]
I have added new cryptocurrency to peatio.
Deposits work well. There was issue similar to https://github.com/peatio/peatio/issues/484 but I fixed it. Now it withdraws but it always shows "accepted". I guess it has to show "processing", "done" but it hasn't.
![screenshot_](https://cloud.githubusercontent.com/assets/4103746/24704276/a26902d0-1a0f-11e7-85a5-536648742961.png)
What is the reason? I didn't found any errors in production.log but these are from peatio/amqp/withdraw_coin.log:
```
E, [2017-04-05T04:04:48.307375 #25223] ERROR -- : Resource temporarily unavailable - read would block (IO::EAGAINWaitReadable)
/home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:41:in `read_nonblock'
/home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:41:in `block in read_fully'
/home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:40:in `loop'
/home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:40:in `read_fully'
/home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/transport.rb:199:in `read_next_frame'
/home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/session.rb:923:in `init_connection'
/home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/session.rb:254:in `start'
/home/ubuntu/peatio/current/lib/daemons/amqp_daemon.rb:17:in `<top (required)>'
/home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/withdraw_coin_ctl:11:in `<main>'
```

UPDATE. Seems like I can ignore *.log according to this https://github.com/peatio/peatio/issues/430#issuecomment-74631086
but peatio/amqp/withdraw_coin.output gives nothing:
```
I, [2017-03-24T21:28:40.205644 #24500]  INFO -- : Connected to AMQP broker (prefetch: default)
Terminating threads ..
Stopped.
peatio:amqp:withdraw_coin: process with pid 20383 started.
I, [2017-03-27T04:37:44.584227 #20383]  INFO -- : Connected to AMQP broker (prefetch: default)
Terminating threads ..
Stopped.
peatio:amqp:withdraw_coin: process with pid 26944 started.
I, [2017-04-03T21:45:50.553229 #26944]  INFO -- : Connected to AMQP broker (prefetch: default)
Terminating threads ..
Stopped.
peatio:amqp:withdraw_coin: process with pid 10435 started.
I, [2017-04-03T22:08:32.097136 #10435]  INFO -- : Connected to AMQP broker (prefetch: default)
Terminating threads ..
Stopped.
peatio:amqp:withdraw_coin: process with pid 25223 started.
I, [2017-04-05T01:03:28.116645 #25223]  INFO -- : Connected to AMQP broker (prefetch: default)
```

**Comment by legends420** [comment]
you have to go into the admin panel and accept the withdraw
