### ISSUE TITLE
ionController::RoutingError (No route matches [GET] "/fonts/bootstrap/glyphicons-halflings-regular.eot")

### ISSUE THREAD

**Issue by melmali2828** [peatio/peatio#557]
Hi,

admin panel login,

[2017-05-03T12:05:30.655535 #5963] FATAL -- :
ActionController::RoutingError (No route matches [GET] "/fonts/bootstrap/glyphicons-halflings-regular.eot"):
  lib/middleware/security.rb:11:in `call'

I, [2017-05-03T12:05:30.773270 #5963]  INFO -- : Started GET "/fonts/bootstrap/glyphicons-halflings-regular.woff" for 141.101.104.229 at 2017-05-03 12:05:30 +0300
F, [2017-05-03T12:05:30.774869 #5963] FATAL -- :
ActionController::RoutingError (No route matches [GET] "/fonts/bootstrap/glyphicons-halflings-regular.woff"):
  lib/middleware/security.rb:11:in `call'

I, [2017-05-03T12:05:30.850651 #5963]  INFO -- : Started GET "/fonts/bootstrap/glyphicons-halflings-regular.ttf" for 141.101.105.44 at 2017-05-03 12:05:30 +0300
F, [2017-05-03T12:05:30.852450 #5963] FATAL -- :
ActionController::RoutingError (No route matches [GET] "/fonts/bootstrap/glyphicons-halflings-regular.ttf"):
  lib/middleware/security.rb:11:in `call'

**Comment by ZenXChaos** [comment]
Did you compile your assets ? 

`rake assets:clean && rake assets:clobber && rake assets:precompile`

**Comment by melmali2828** [comment]
yes, I've done it many times

**Comment by freshmurry** [comment]
I'm getting the same error, no resolution yet?

**Comment by sgoldens** [comment]
Seeing this error in a production full-stack rails 5 app, only sparingly, but still seeing it

F, [2018-04-12T16:40:48.517419 #9384] FATAL -- : [03a9de77-1252-4b4d-ab82-eff03c7763b6] ActionController::RoutingError (No route matches [GET] "/fonts/bootstrap/glyphicons-halflings-regular.eot"):
