### ISSUE TITLE
help,NameError: uninitialized constant ActiveRecord::Type

### ISSUE THREAD

**Issue by brewswang** [peatio/peatio#566]
bundle exec rake db:setup
W, [2017-06-02T15:47:10.300158 #3983]  WARN -- : You are setting a key that conflicts with a built-in method OmniAuth::AuthHash::InfoHash#name defined at /home/wangchen/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/omniauth-1.2.2/lib/omniauth/auth_hash.rb:34. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method.
/home/wangchen/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 60 was converted to "60". (StructuredWarnings::StandardWarning)
/home/wangchen/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 8080 was converted to "8080". (StructuredWarnings::StandardWarning)
/home/wangchen/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 347851 was converted to "347851". (StructuredWarnings::StandardWarning)
/home/wangchen/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 80 was converted to "80". (StructuredWarnings::StandardWarning)
/home/wangchen/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 80 was converted to "80". (StructuredWarnings::StandardWarning)
/home/wangchen/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 443 was converted to "443". (StructuredWarnings::StandardWarning)
/home/wangchen/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. true was converted to "true". (StructuredWarnings::StandardWarning)
/home/wangchen/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. true was converted to "true". (StructuredWarnings::StandardWarning)
/home/wangchen/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 3820920586 was converted to "3820920586". (StructuredWarnings::StandardWarning)
peatio_development already exists
peatio_test already exists
rake aborted!
NameError: uninitialized constant ActiveRecord::Type
/home/wangchen/peatio/app/models/deposit.rb:4:in `extend'
/home/wangchen/peatio/app/models/deposit.rb:4:in `<class:Deposit>'
/home/wangchen/peatio/app/models/deposit.rb:1:in `<top (required)>'
/home/wangchen/peatio/app/observers/transfer_observer.rb:2:in `<class:TransferObserver>'
/home/wangchen/peatio/app/observers/transfer_observer.rb:1:in `<top (required)>'
/home/wangchen/peatio/config/environment.rb:5:in `<top (required)>'
/home/wangchen/.rbenv/versions/2.2.1/bin/bundle:23:in `load'
/home/wangchen/.rbenv/versions/2.2.1/bin/bundle:23:in `<main>'
Tasks: TOP => db:setup => db:schema:load_if_ruby => environment
(See full trace by running task with --trace)

**Comment by muhammednagy** [comment]
what did you do since cloning the repo?

**Comment by McGrady00H** [comment]
same problem with macos sierra.

**Comment by hotblade** [comment]
same problem here with MacOS Sierra.
Initially it puts this message with `gem 'mysql2'`

Couldn't create database for {"adapter"=>"mysql2", "encoding"=>"utf8", "database"=>"peatio_development", "username"=>"root", "password"=>"jd;eaotw", "pool"=>10, "reconnect"=>true}
Specified 'mysql2' for database adapter, but the gem is not loaded. Add `gem 'mysql2'` to your Gemfile.

After I changed the Gemfile like `gem 'mysql2', '~> 0.3.8'`, it could create two databases but it couldn't create any table at all. At this moment, the error message was same as that of brewswang.

**Comment by muhammednagy** [comment]
Try my fork

**Comment by nomiAA** [comment]
I have the same problem I tried to install the fork of @muhammednagy  but the error still appears.
Who knows how to solve it

> Couldn't create database for {"adapter"=>"mysql2", "encoding"=>"utf8", "database"=>"peatio_development", "username"=>"root", "password"=>nil, "pool"=>10, "reconnect"=>true}, {:charset=>"utf8", :collation=>"utf8_unicode_ci"}
> (If you set the charset manually, make sure you have a matching collation)
> Couldn't create database for {"adapter"=>"mysql2", "encoding"=>"utf8", "database"=>"peatio_test", "username"=>"root", "password"=>nil, "pool"=>10, "reconnect"=>true}, {:charset=>"utf8", :collation=>"utf8_unicode_ci"}
> (If you set the charset manually, make sure you have a matching collation)
> rake aborted!
> NameError: uninitialized constant ActiveRecord::Type
> /home/nomi/peatiom/peatio-master/app/models/deposit.rb:4:in `extend'
> /home/nomi/peatiom/peatio-master/app/models/deposit.rb:4:in `<class:Deposit>'
> /home/nomi/peatiom/peatio-master/app/models/deposit.rb:1:in `<top (required)>'
> /home/nomi/peatiom/peatio-master/app/observers/transfer_observer.rb:2:in `<class:TransferObserver>'
> /home/nomi/peatiom/peatio-master/app/observers/transfer_observer.rb:1:in `<top (required)>'
> /home/nomi/peatiom/peatio-master/config/environment.rb:5:in `<top (required)>'

**Comment by muhammednagy** [comment]
this is on MacOS?
I didn't try MacOS before

**Comment by nomiAA** [comment]
no, i am using ubnutu

**Comment by nomiAA** [comment]
Ok, i found the solution here :
https://chat.stackoverflow.com/rooms/148122/discussion-between-illusionist-and-tomislav-mikulin

you need to change the version of enumerize in the Gemfile

**Comment by muhammednagy** [comment]
Ubuntu?
I setup like 5 or 6 Ubuntu servers a month and didn't change anything

**Comment by nomiAA** [comment]
I'm new to linux and ruby, I have no idea:(
Maybe it's because we have different versions of Ruby or Mysql

**Comment by muhammednagy** [comment]
we don't have different versions of mysql
if you followed my document correctly you would have ruby 2.2.1
i use rbenv
try the production document too

**Comment by sadflask** [comment]
I get this same error, didn't initially get it but after running a few times it has shown up. What did you do to fix this? The version of enumerize in the file is the most recent?

**Comment by muhammednagy** [comment]
@nomiAA what was the version that worked with you?
I moved to OS X and I'm trying to get it working

**Comment by muhammednagy** [comment]
@brewswang did you manage to fix it?

**Comment by sadflask** [comment]
1.1.1 works for me @muhammednagy

**Comment by saraomb** [comment]
@muhammednagy  I installed the wrong version of Ruby (2.2.3) this is why I got the error
Try to reinstall all things and see that you do not have any errors

you can try also to change the version of enumerize in the Gemfile to an older version and run again bundle update, This solved my problem when I used version 2.2.3

**Comment by MaffeProg** [comment]
No this isn't why you got the error. I installed everything. I though about upgrading bootstrap. When I did I found out many code is outdated and needed to be upgraded.

**Comment by Shraddha-RoR** [comment]
getting the same error /home/.rvm/gems/ruby-2.2.2/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 443 was converted to "443". (StructuredWarnings::StandardWarning)
/home/.rvm/gems/ruby-2.2.2/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. true was converted to "true". (StructuredWarnings::StandardWarning)
/home/.rvm/gems/ruby-2.2.2/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. true was converted to "true". (StructuredWarnings::StandardWarning)
/home/.rvm/gems/ruby-2.2.2/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 3820920586 was converted to "3820920586". (StructuredWarnings::StandardWarning)
  I  used the rvm 2.2.2 on ubantu. while rake db:migration getting errors

**Comment by chetantete** [comment]
/home/.rvm/gems/ruby-2.2.2/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 8080 was converted to "8080". (StructuredWarnings::StandardWarning)
/home/.rvm/gems/ruby-2.2.2/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 65910 was converted to "65910". (StructuredWarnings::StandardWarning)
/home/.rvm/gems/ruby-2.2.2/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 80 was converted to "80". (StructuredWarnings::StandardWarning)
/home/.rvm/gems/ruby-2.2.2/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 80 was converted to "80". (StructuredWarnings::StandardWarning)
/home/.rvm/gems/ruby-2.2.2/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 443 was converted to "443". (StructuredWarnings::StandardWarning)
/home/.rvm/gems/ruby-2.2.2/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. true was converted to "true". (StructuredWarnings::StandardWarning)
/home.rvm/gems/ruby-2.2.2/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. true was converted to "true". (StructuredWarnings::StandardWarning)
/home/.rvm/gems/ruby-2.2.2/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 3820920586 was converted to "3820920586". (StructuredWarnings::StandardWarning)
  getting warnings on ubuntu while running rake db:migrate using vrm 2.2.2 as getting errro while bundling for redis .
but now not able migrate the files

**Comment by scatterp** [comment]
the warnings are because you did not use "s in your config files..

**Comment by Shraddha-RoR** [comment]
@scatterp  didn't get what you want suggest. I have /home/.rvm/gems/ruby-2.2.2/gems/figaro-1.1.1/lib/figaro/application.rb file, if I open file there is method  set(key, value) converting to string

**Comment by chetantete** [comment]
@scatterp didn't get what you want suggest. I have /home/.rvm/gems/ruby-2.2.2/gems/figaro-1.1.1/lib/figaro/application.rb file, if I open file there is method set(key, value) converting to string

**Comment by scatterp** [comment]
the settings you entered in to yml for example application.yml you need "s

**Comment by cyzanfar** [comment]
Gemfile:

`gem 'enumerize', '~> 1.1.1'`

then:

`$ bundle install`

Worked for me

**Comment by csander83** [comment]
@cyzanfar Thank you for help!
