### ISSUE TITLE
Undefined method `sum' for nil:NilClass

### ISSUE THREAD

**Issue by nomiAA** [peatio/peatio#588]
I just installed the project, and when I click on the " Solvency" tab I get the error 
"undefined method `sum' for nil:NilClass"
in page app/views/private/assets/_liability_tabs.html.slim ,code `:@btc_proof.sum`

Does anyone know how to fix it?

**Comment by Jfaler** [comment]
The error is removed once you install the production server.

**Comment by muhammednagy** [comment]
did you try RAILS_ENV=production rake solvency:liability_proof?

**Comment by Jfaler** [comment]
@taiwo Why did you downvote my contribution? I spent 30 minutes helping you setup bitcoin for your server on gitter today. lol.  I could have said nothing.

**Comment by chinacoinbase** [comment]
where to setting about it,

**Comment by chinacoinbase** [comment]
add "RAILS_ENV=production rake solvency:liability_proof" to which file? thanks

**Comment by scatterp** [comment]
Add this task to your crontab so it runs regularly
https://vexxhost.com/resources/tutorials/how-to-use-cron-jobs-for-automation-on-ubuntu-14-04/

**Comment by chinacoinbase** [comment]
thanks, but the problem is the same when i done this.

**Comment by ShiningBomb** [comment]
run rake solvency:liability_proof mate

**Comment by KelvinLiangAtFDTAI** [comment]
@ShiningBomb 

Great!! It works for me to run the mentioned command.

**Comment by vitorgamer58** [comment]
i try this command and i get the same...

**Comment by vitorgamer58** [comment]
```
I, [2018-06-21T17:05:09.974335 #20877]  INFO -- : Started GET "/exchange_assets" for 108.162.212.220 at 2018-06-21 17:05:09 +0000
I, [2018-06-21T17:05:09.975471 #20877]  INFO -- : Processing by Private::AssetsController#index as HTML
I, [2018-06-21T17:05:09.991904 #20877]  INFO -- :   Rendered private/assets/_liability_data.html.slim (2.3ms)
I, [2018-06-21T17:05:09.992705 #20877]  INFO -- :   Rendered private/assets/_liability_tabs.html.slim (3.4ms)
I, [2018-06-21T17:05:09.992758 #20877]  INFO -- :   Rendered private/assets/_liability_proof.html.slim (3.7ms)
I, [2018-06-21T17:05:09.992801 #20877]  INFO -- :   Rendered private/assets/index.html.slim within layouts/application (4.0ms)
I, [2018-06-21T17:05:09.992884 #20877]  INFO -- : Completed 500 Internal Server Error in 17ms
F, [2018-06-21T17:05:09.993877 #20877] FATAL -- :
ActionView::Template::Error (undefined method `sum' for nil:NilClass):
    19:         span.title = t('.iop-assets-total')
    20:         span.currency
    21:           == t("currency.icon.iop")
    22:           = @iop_proof.sum
    23:       = render 'liability_data', account: @iop_account, proof: @iop_proof
    24:
    25:     #cny-proof.tab-pane:        .trade-wrapper
  app/views/private/assets/_liability_tabs.html.slim:22:in `_app_views_private_assets__liability_tabs_html_slim__4306570663942302592_46991503637480'
  app/views/private/assets/_liability_proof.html.slim:10:in `_app_views_private_assets__liability_proof_html_slim__514583292708819126_46991503263780'
  app/views/private/assets/index.html.slim:14:in `block in _app_views_private_assets_index_html_slim__2635018968175595278_46991501137400'
  app/views/private/assets/index.html.slim:1:in `_app_views_private_assets_index_html_slim__2635018968175595278_46991501137400'
  lib/middleware/security.rb:11:in `call'

```

**Comment by vitorgamer58** [comment]
and now

```
Psych::SyntaxError ((/home/deploy/peatio/current/config/deposit_channels.yml): did not find expected key while parsing a block mapping at line 23 column 3):
  app/controllers/private/funds_controller.rb:10:in `index'
  lib/middleware/security.rb:11:in `call'
```
https://github.com/Brexchange/Brexchange/blob/stable/config/deposit_channels.yml

**Comment by vitorgamer58** [comment]
```
*** Start dash liability proof generation ***
Complete.
rake aborted!
Don't know how to build task 'mate'

```
