### ISSUE TITLE
When I click on my asset and trading hall, the program exits automatically。

### ISSUE THREAD

**Issue by wyj1226** [peatio/peatio#594]

**Comment by onlyyouandty** [comment]
Those don't work in the local environment. You have to deploy to production to have them work + get bitcoind working.

**Comment by wyj1226** [comment]
How to deploy?

**Comment by onlyyouandty** [comment]
https://files.gitter.im/peatio/peatio/OIAr/Documentation-of-the-process-of-creating-a-Peatio-Exchange.odt

**Comment by onlyyouandty** [comment]
@wyj1226, I just got to know you can run the trading page locally as well. By using ruby version `2.2.7`. You can install that with `rbenv install 2.2.7`. Thanks to @takinbo.

**Comment by wyj1226** [comment]
I install 2.3.3.but,  I can't run the trading page locally as well,
Maybe what needs to be configured?

**Comment by wyj1226** [comment]
@onlyyouandty When I execute ”sudo npm -g install bitgod“ ,There was a mistake:TypeError: Object function Object() { [native code] } has no method 'assign'
    at Object.<anonymous> (/usr/lib/node_modules/npm/lib/config/cmd-list.js:113:33)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /usr/lib/node_modules/npm/lib/npm.js:36:17
    at Object.<anonymous> (/usr/lib/node_modules/npm/lib/npm.js:470:3)
    at Module._compile (module.js:456:26)
