### ISSUE TITLE
Muhanmmed's Eth not working

### ISSUE THREAD

**Issue by ravil1991t** [peatio/peatio#610]
His eth is not working; in detail filter.service not working.
Filter.service runs service.js, but in there, "Filter not found" error appears.

**Comment by tihualong** [comment]
did you run the npm command to install the web3.js?

**Comment by ravil1991t** [comment]
@tihualong 
yes
i installed web3.js

**Comment by tihualong** [comment]
your error Log for details?

**Comment by ravil1991t** [comment]
{"message":"filter not found","stack":"Error: filter not found\n    at Object.InvalidResponse (/home/ubuntu/web3/node_modules/web3/lib/web3/errors.js:38:16)\n    at /home/ubuntu/web3/node_modules/web3/lib/web3/requestmanager.js:255:40\n    at Array.filter (native)\n    at /home/ubuntu/web3/node_modules/web3/lib/web3/requestmanager.js:252:12\n    at XMLHttpRequest.request.onreadystatechange (/home/ubuntu/web3/node_modules/web3/lib/web3/httpprovider.js:118:13)\n    at XMLHttpRequestEventTarget.dispatchEvent (/home/ubuntu/web3/node_modules/xhr2/lib/xhr2.js:64:18)\n    at XMLHttpRequest._setReadyState (/home/ubuntu/web3/node_modules/xhr2/lib/xhr2.js:354:12)\n    at XMLHttpRequest._onHttpResponseEnd (/home/ubuntu/web3/node_modules/xhr2/lib/xhr2.js:509:12)\n    at IncomingMessage.<anonymous> (/home/ubuntu/web3/node_modules/xhr2/lib/xhr2.js:469:24)\n    at emitNone (events.js:91:20)","level":"error","timestamp":"2017-09-15T20:03:33.500Z"}

**Comment by tihualong** [comment]
seems like your ethereum process threw an error,the web3.js cannot parse the result

**Comment by ravil1991t** [comment]
It is from filter in service.js

**Comment by nomgbr** [comment]
Is there any documentation how to run ETH server?

**Comment by Apollo-IT** [comment]
I've already developed and deployed 3 exchanges based on Peatio.
I can add more coins and customize exchanges with peatio.
Also have experiences in wlox.
Feel free to message me any time.
**skype : live:apollo447722
mail : [apollo447722@outlook.com](mailto:apollo447722@outlook.com)**
Regards.
