### ISSUE TITLE
Using Bitcoind in a new server

### ISSUE THREAD

**Issue by rgtoffolo** [peatio/peatio#634]
Hey guys, I'm trying to configure a new server to run Bitcoind and RabbitMq giving some more security to the wallet.dat. I've already created the server and installed the resources. Using testnet, I'm receiving the coin deposits but the RPC notifications are not arriving on the Peatio Server. I'm receiving the error message below:

FATAL -- : CoinRPC::ConnectionRefusedError (CoinRPC::ConnectionRefusedError)
/home/ubuntu/peatio/app/services/coin_rpc.rb:48:in `rescue in http_post_request'
/home/ubuntu/peatio/app/services/coin_rpc.rb:41:in `http_post_request'
/home/ubuntu/peatio/app/services/coin_rpc.rb:33:in `handle'
/home/ubuntu/peatio/app/services/coin_rpc.rb:23:in `method_missing'
/home/ubuntu/peatio/app/models/worker/deposit_coin.rb:60:in `get_raw'
/home/ubuntu/peatio/app/models/worker/deposit_coin.rb:13:in `process'

**Comment by scatterp** [comment]
using which repo ?

**Comment by rgtoffolo** [comment]
I'm sorry but I didn't understand your question. I'm using the default installation of peatio. The bitcoind server is an Ubuntu 16.04 and the Peatio server is an Ubuntu 14.04. ... At the bitcoind server, if I try to re-run the rabbitmqadmin command to notify the satoshi channel, I receive the message "Message Published"

/usr/local/sbin/rabbitmqadmin --host=<my hot IP> publish routing_key=peatio.deposit.coin payload='{"txid":"<transaction ID>", "channel_key":"satoshi"}'

... but at the Peatio server the RPC shows "connection refused"

**Comment by rgtoffolo** [comment]
Hey guys. Just comming back to tell that I've had success configuring new servers. Now I'm using Peatio with 3 different servers. One for webpages, another one for bitcoind and rabbitmq and a third one for MySql. Everything is working fine. I'm preparing a doc with all configurations needed to this environment because I believe that this can help to improve the system security. I'll ask for adding a new configuration doc here soon.

**Comment by felipecaldas** [comment]
That's great, good job. Which fork are you using?
Looking forward to seeing your installation manual.

**Comment by CowboyKen** [comment]
Good Work Guys.  Nice to see this is coming along.

**Comment by scatterp** [comment]
rgtoffolo you are using very out dated code please switch to muhammednagy/peatio or scatterp/peatio
regarding your doc please place it in the issues section of scatterp/peatio and i will add it to the active repos thank you for your hard work

note: you can install from my repo with a single command

**Comment by rgtoffolo** [comment]
scatterp, thank you for your advice. I'll proceed with a new patio installation using one of the repos that you've mentioned.

Follow bellow the instructions to configure Peatio using 3 servers.
-----------------
- First Server - MySql
     Just install MySql using procedures as Peatio installation described 

- Second Server - Bitcoind & RabbitMQ

     Install Bitcoind
     Install RabbitMQ
     Follow the instructions to create Bitcoin.conf
     Add a new line in Bitcoin.conf:
          rpcallowip=[IP address or dns name of your Peatio Webserver]

- Third Server - Peatio Webserver

     Install Peatio using the default procedures but do not install MySql, Bitcoind and RabbitMQ
     Add a new line in database.yml
          host: [IP address or dns name of your MySql Server]
          ***you need to add this configuration before running the databse creation commands

     Change the configuration in currencies.yml
          rpc: [username]:[password]@[IP address of your RabbitMQ server]:18332 
     
     Change the configuration in amqp.yml
          host: [IP address or dns name of your RabbitMQ server]

     restart all daemons.

**Comment by scatterp** [comment]
thanks

**Comment by scatterp** [comment]
https://github.com/scatterp/peatio/blob/master/MultiServerReadme.md

**Comment by felipecaldas** [comment]
Nice one guys

On 31 Oct. 2017 7:42 am, "scatterp" <notifications@github.com> wrote:

https://github.com/scatterp/peatio/blob/master/MultiServerReadme.md

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/peatio/peatio/issues/634#issuecomment-340577833>, or mute
the thread

**Comment by scatterp** [comment]
@rgtoffolo  could you try and separate the server and web client?

**Comment by rgtoffolo** [comment]
@scatterp I don't know if we can segregate the server and web client on peatio as it is. I believe that is an architectural issue. Do you have a different opinion ?

**Comment by scatterp** [comment]
the website seems to use javascript html and css for a lot of its functionality 
some where there must be some other code i guess ruby which is used to pass information to the server
to set the server up simply install dont visit the page and check unix time stamps for last access that way all the server files can be kept the others deleted potentially 

for the client side it might need some adaption but i had reasonable results copying the html and css and placing it in a online css editor i think if you add javascript to that mix you have then a client which is running on another server but wont connect ... but i doubt its really missing much to do so if you set up a ruby on the rails web server place the same code there and add to it ruby api client 
you have the functionality to "do stuff" and from there some coding will be required but i dont think its much the point is if you use that unix time stamp trick to seperate out and delete what is the server you remove all the css js and other stuff you will be left with a few files that need changing..

**Comment by sushilraghav** [comment]
@rgtoffolo  ///  I can help you. I am having a vast experience in Peatio, Crypto Currency exchange and trading platforms with FIAT currency based on Bitcoin, litecoin, Ethereum, XRP etc, Core Wallets and Daemons. I am having expertise in ICO ie Initial Coin Offering full system development, White Paper creation with full architecture and high level documentation, smart contract writing and many more skills.

My Skype : sushilraghav and email is admin@rensoftglobal.com
