### ISSUE TITLE
peatio/doc/deploy-production-server.md no longer works due to recent updates

### ISSUE THREAD

**Issue by ytrezq** [peatio/peatio#677]
ytrezq@txbit:~/peatio$ bundle exec rake db:setup --trace
    W, [2017-12-27T11:18:57.999364 #1096]  WARN -- : You are setting a key that conflicts with a built-in method OmniAuth::AuthHash::InfoHash#name defined at /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/omniauth-1.2.2/lib/omniauth/auth_hash.rb:34. This can cause unexpected behavior when accessing the key as a property. You can still access the key via the #[] method.
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 60 was converted to "60". (StructuredWarnings::StandardWarning)
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 8080 was converted to "8080". (StructuredWarnings::StandardWarning)
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 65910 was converted to "65910". (StructuredWarnings::StandardWarning)
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 80 was converted to "80". (StructuredWarnings::StandardWarning)
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 80 was converted to "80". (StructuredWarnings::StandardWarning)
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 443 was converted to "443". (StructuredWarnings::StandardWarning)
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. true was converted to "true". (StructuredWarnings::StandardWarning)
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. true was converted to "true". (StructuredWarnings::StandardWarning)
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 3820920586 was converted to "3820920586". (StructuredWarnings::StandardWarning)
    ** Invoke db:setup (first_time)
    ** Invoke db:schema:load_if_ruby (first_time)
    ** Invoke db:create (first_time)
    ** Invoke db:load_config (first_time)
    ** Execute db:load_config
    ** Execute db:create
    Specified 'mysql2' for database adapter, but the gem is not loaded. Add `gem 'mysql2'` to your Gemfile.
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/connection_specification.rb:58:in `rescue in resolve_hash_connection'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/connection_specification.rb:55:in `resolve_hash_connection'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/connection_specification.rb:34:in `spec'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.13/lib/active_record/connection_handling.rb:39:in `establish_connection'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.13/lib/active_record/tasks/mysql_database_tasks.rb:8:in `establish_connection'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.13/lib/active_record/tasks/mysql_database_tasks.rb:15:in `create'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.13/lib/active_record/tasks/database_tasks.rb:73:in `create'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.13/lib/active_record/tasks/database_tasks.rb:87:in `block in create_current'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.13/lib/active_record/tasks/database_tasks.rb:183:in `block in each_current_configuration'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.13/lib/active_record/tasks/database_tasks.rb:182:in `each'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.13/lib/active_record/tasks/database_tasks.rb:182:in `each_current_configuration'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.13/lib/active_record/tasks/database_tasks.rb:86:in `create_current'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.13/lib/active_record/railties/databases.rake:20:in `block (2 levels) in <top (required)>'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `call'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `block in execute'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `each'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `execute'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
    /home/ytrezq/.rbenv/versions/2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:217:in `block in invoke_prerequisites'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:215:in `each'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:215:in `invoke_prerequisites'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
    /home/ytrezq/.rbenv/versions/2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:217:in `block in invoke_prerequisites'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:215:in `each'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:215:in `invoke_prerequisites'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
    /home/ytrezq/.rbenv/versions/2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:181:in `invoke'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/application.rb:160:in `invoke_task'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block (2 levels) in top_level'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `each'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block in top_level'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/application.rb:125:in `run_with_threads'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/application.rb:110:in `top_level'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/application.rb:83:in `block in run'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/application.rb:80:in `run'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/bin/rake:23:in `load'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/bin/rake:23:in `<top (required)>'
    /home/ytrezq/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
    /home/ytrezq/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'
    /home/ytrezq/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'
    /home/ytrezq/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'
    /home/ytrezq/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
    /home/ytrezq/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
    /home/ytrezq/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
    /home/ytrezq/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
    /home/ytrezq/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
    /home/ytrezq/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
    /home/ytrezq/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
    /home/ytrezq/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
    /home/ytrezq/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
    /home/ytrezq/.rbenv/versions/2.2.2/bin/bundle:23:in `load'
    /home/ytrezq/.rbenv/versions/2.2.2/bin/bundle:23:in `<main>'
    Couldn't create database for {"adapter"=>"mysql2", "encoding"=>"utf8", "database"=>"peatio_production", "username"=>"root", "password"=>nil, "pool"=>10, "reconnect"=>true}
    rake aborted!
    Gem::LoadError: Specified 'mysql2' for database adapter, but the gem is not loaded. Add `gem 'mysql2'` to your Gemfile.
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/connection_specification.rb:58:in `rescue in resolve_hash_connection'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/connection_specification.rb:55:in `resolve_hash_connection'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/connection_specification.rb:46:in `resolve_string_connection'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/connection_specification.rb:32:in `spec'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.13/lib/active_record/connection_handling.rb:39:in `establish_connection'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.13/lib/active_record/tasks/database_tasks.rb:89:in `create_current'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.13/lib/active_record/railties/databases.rake:20:in `block (2 levels) in <top (required)>'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `call'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `block in execute'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `each'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `execute'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
    /home/ytrezq/.rbenv/versions/2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:217:in `block in invoke_prerequisites'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:215:in `each'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:215:in `invoke_prerequisites'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
    /home/ytrezq/.rbenv/versions/2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:217:in `block in invoke_prerequisites'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:215:in `each'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:215:in `invoke_prerequisites'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
    /home/ytrezq/.rbenv/versions/2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:181:in `invoke'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/application.rb:160:in `invoke_task'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block (2 levels) in top_level'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `each'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block in top_level'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/application.rb:125:in `run_with_threads'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/application.rb:110:in `top_level'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/application.rb:83:in `block in run'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/application.rb:80:in `run'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/bin/rake:23:in `load'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/bin/rake:23:in `<top (required)>'
    /home/ytrezq/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
    /home/ytrezq/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'
    /home/ytrezq/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'
    /home/ytrezq/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'
    /home/ytrezq/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
    /home/ytrezq/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
    /home/ytrezq/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
    /home/ytrezq/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
    /home/ytrezq/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
    /home/ytrezq/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
    /home/ytrezq/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
    /home/ytrezq/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
    /home/ytrezq/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
    /home/ytrezq/.rbenv/versions/2.2.2/bin/bundle:23:in `load'
    /home/ytrezq/.rbenv/versions/2.2.2/bin/bundle:23:in `<main>'

    Caused by:
    Gem::LoadError: can't activate mysql2 (~> 0.3.10), already activated mysql2-0.4.10. Make sure all dependencies are added to Gemfile.
    /home/ytrezq/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/rubygems_integration.rb:404:in `block (2 levels) in replace_gem'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/mysql2_adapter.rb:3:in `<top (required)>'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `require'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `block in require'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:214:in `load_dependency'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `require'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/connection_specification.rb:56:in `resolve_hash_connection'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/connection_specification.rb:46:in `resolve_string_connection'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/connection_specification.rb:32:in `spec'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.13/lib/active_record/connection_handling.rb:39:in `establish_connection'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.13/lib/active_record/tasks/database_tasks.rb:89:in `create_current'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.13/lib/active_record/railties/databases.rake:20:in `block (2 levels) in <top (required)>'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `call'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `block in execute'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `each'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `execute'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
    /home/ytrezq/.rbenv/versions/2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:217:in `block in invoke_prerequisites'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:215:in `each'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:215:in `invoke_prerequisites'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
    /home/ytrezq/.rbenv/versions/2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:217:in `block in invoke_prerequisites'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:215:in `each'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:215:in `invoke_prerequisites'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
    /home/ytrezq/.rbenv/versions/2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/task.rb:181:in `invoke'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/application.rb:160:in `invoke_task'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block (2 levels) in top_level'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `each'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block in top_level'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/application.rb:125:in `run_with_threads'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/application.rb:110:in `top_level'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/application.rb:83:in `block in run'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/lib/rake/application.rb:80:in `run'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/bin/rake:23:in `load'
    /home/ytrezq/peatio/vendor/bundle/ruby/2.2.0/bin/rake:23:in `<top (required)>'
    /home/ytrezq/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
    /home/ytrezq/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'
    /home/ytrezq/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'
    /home/ytrezq/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'
    /home/ytrezq/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
    /home/ytrezq/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
    /home/ytrezq/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
    /home/ytrezq/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
    /home/ytrezq/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
    /home/ytrezq/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
    /home/ytrezq/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
    /home/ytrezq/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
    /home/ytrezq/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
    /home/ytrezq/.rbenv/versions/2.2.2/bin/bundle:23:in `load'
    /home/ytrezq/.rbenv/versions/2.2.2/bin/bundle:23:in `<main>'
    Tasks: TOP => db:setup => db:schema:load_if_ruby => db:create

Of course, just changing version requirements doesn’t works.

**Comment by muhammednagy** [comment]
please check my fork
i've updated the docs

**Comment by frezeq00** [comment]
bittrex opensource: https://github.com/pkdcryptos/frezeq0_bittrex-opensource
