### ISSUE TITLE
bundle exec rake daemons:start

### ISSUE THREAD

**Issue by zaidragie** [peatio/peatio#688]
good day 
i cant seem to understand what is wrong i keep getting the following out put when i run "bundle exec rake daemons:start"

rake aborted!
Psych::SyntaxError: (<unknown>): did not find expected key while parsing a block mapping at line 6 column 3
/home/zaid/peatio/config/application.rb:15:in `<module:Peatio>'
/home/zaid/peatio/config/application.rb:14:in `<top (required)>'
/home/zaid/peatio/Rakefile:5:in `require'
/home/zaid/peatio/Rakefile:5:in `<top (required)>'
/home/zaid/.rbenv/versions/2.2.2/bin/bundle:23:in `load'
/home/zaid/.rbenv/versions/2.2.2/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)

**Comment by oskanddr** [comment]
Hello @zaidragie,

Peatio is known to have ugly daemons implementation. My team has worked for this issue and made improvements. I can help you with Peatio deployment & development.

You can always reach me at nimpo1074@gmail.com

Best,
Oskar

**Comment by frezeq00** [comment]
bittrex opensource: https://github.com/pkdcryptos/frezeq0_bittrex-opensource

**Comment by wozzi** [comment]
Hello,

Did you manager to resolve this? I seem to have exactly the same issue.

Regards
Warren

**Comment by zaidragie** [comment]
Nope unfortunately I didn't

**Comment by algobasket** [comment]
@zaidragie 
Complete Peatio Help | Support | Bug Fixing
http://peatio.algobasket.com
Free Technical Documentation below :
https://github.com/peatio/peatio/files/2457278/PeatioCryptoExchange.pdf
https://www.youtube.com/watch?v=tpieNIMSBuQ
https://github.com/algobasket/PeatioCryptoExchange/
Contact me on Skype : algobasket
Thanks in advance !!!
