### ISSUE TITLE
Daemons dont start

### ISSUE THREAD

**Issue by pavlealeksic** [peatio/peatio#693]
Hi there,
when I run the command for starting all daemons it just gives me a blank line, and in the logs I see this:
Logfile created on 2018-01-11 16:36:53 +0000 by logger.rb/47272
I, [2018-01-11T16:36:53.619663 #28489]  INFO -- : *** below you find the most recent exception thrown, this will be likely (but not certainly) the exception that made the$E, [2018-01-11T16:36:53.619784 #28489] ERROR -- : Bad file descriptor (Errno::EBADF)
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/daemonize.rb:137:in `for_fd'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/daemonize.rb:137:in `block in close_io'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/daemonize.rb:137:in `initialize'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/daemonize.rb:137:in `new'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/daemonize.rb:137:in `close_io'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/daemonize.rb:109:in `daemonize'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/application.rb:146:in `start_load'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'

Whats the solution for this?
Regards,
Pavle

**Comment by scatterp** [comment]
you can use http://github.com/scatterp/peatio the main repo is very old...

**Comment by algobasket** [comment]
@pavlealeksic 
Complete Peatio Help | Support | Bug Fixing
http://peatio.algobasket.com
Free Technical Documentation below :
https://github.com/peatio/peatio/files/2457278/PeatioCryptoExchange.pdf
https://www.youtube.com/watch?v=tpieNIMSBuQ
https://github.com/algobasket/PeatioCryptoExchange/
Contact me on Skype : algobasket
Thanks in advance !!!
