### ISSUE TITLE
Adding Ethereum 

### ISSUE THREAD

**Issue by skaleita** [peatio/peatio#697]
Can anyone point me in the right direction on how to add Ethereum to Peatio

**Comment by scatterp** [comment]
yes contact me on skype simon.m.day

**Comment by oskanddr** [comment]
Hello @skaleita,

I have beta version for ETH support on Peatio. I believe I can help you with this.

You can always reach me at nimpo1074@gmail.com

Best,
Oskar

**Comment by muhammednagy** [comment]
hello 
please check my fork 
i've added ethereum and i have documented it 
if u are stuck mail me and i will help you 
i'm not offering business i just wanna help

**Comment by Apollo-IT** [comment]
I've already developed and deployed 3 exchanges based on Peatio.
I can add more coins and customize exchanges with peatio.
Also have experiences in wlox.
Feel free to message me any time.
**skype : live:apollo447722
mail : [apollo447722@outlook.com](mailto:apollo447722@outlook.com)**
Regards.

**Comment by sharmaabhishek2207** [comment]
Hi @muhammednagy 

It will be great if you can share the steps to configure ethereum with peatio. In peatio setup documentation, only bitcoin setup is provided.

Regards
Abhishek

**Comment by muhammednagy** [comment]
I did !
Check InfraexDev/peatio

**Comment by sharmaabhishek2207** [comment]
Do you mean I need to follow below url?
https://github.com/InfraexDev/peatio/blob/stable/doc/eth.md

If yes, then is there any configuration that i have to do at Peatio's end?

Regards
Abhishek

**Comment by muhammednagy** [comment]
Yes
Check the document please

**Comment by sharmaabhishek2207** [comment]
Sure MuhammedNagy.. i will give it a shot.

Also is there any way to configure quorum private blockchain with Peatio? Kindly let me know if there are any steps to follow to achieve it.

Regards
Abhishek

**Comment by sharmaabhishek2207** [comment]
Hi MuhammadNagy,

 I tried to follow the document for Ethereum setup but it didn't work with Ubuntu 14. I updated my OS version to 16 and follow the documents to setup the peatio again. But it started giving error. While executing the below command, 

bundle exec rake db:setup
but it gives below error message.
ActiveRecord::StatementInvalid: Mysql2::Error: Unknown column 'taggings_count' in 'field list': UPDATE `tags` SET `taggings_count` = COALESCE(`taggings_count`, 0) + 1 WHERE `tags`.`id` = 1
/home/ubuntu/.rvm/gems/ruby-2.5.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:80:in `_query'
/home/ubuntu/.rvm/gems/ruby-2.5.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:80:in `block in query'
/home/ubuntu/.rvm/gems/ruby-2.5.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:79:in `handle_interrupt'
/home/ubuntu/.rvm/gems/ruby-2.5.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:79:in `query'
/h

On google i found that if we run the below command, it will resolve the above issue.
rake acts_as_taggable_on_engine:install:migrations

but it gives below error message.
rake aborted!
Unable to find a spec satisfying thread_safe (~> 0.1.3)  (>= 0) in the set. Perhaps the lockfile is corrupted?
/home/ubuntu/.rvm/gems/ruby-2.5.0/gems/bundler-1.16.1/lib/bundler/spec_set.rb:40:in `block in for'
/home/ubuntu/.rvm/gems/ruby-2.5.0/gems/bundler-1.16.1/lib/bundler/spec_set.rb:25:in `loop'
/home/ubuntu/.rvm/gems/ruby-2.5.0/gems/bundler-1.16.1/lib/bundler/spec_set.rb:25:in `for'


Please help me in setting up peatio on ubuntu 16 so that i can proceed with ETH setup.

Regards
Abhishek

**Comment by muhammednagy** [comment]
what branch are you using?

**Comment by sharmaabhishek2207** [comment]
I am using below command to get the Peatio code.

sudo git clone git://github.com/InfraexDev/peatio.git

**Comment by sharmaabhishek2207** [comment]
Hi Muhammadnagy,

I had reinstalled my OS and followed all the steps from scratch. Post this, it started working fine. Thanks for the wonderful job.

But when i started the server in deamon mode, then the menu options didn't work. For example, when i click on "Trade" it gives the below error.

No such file or directory @ rb_sysopen - app/views/private/markets/show.json.jbuilder

Any idea, what could be the reason?

**Comment by frezeq0** [comment]
bittrex opensource: https://github.com/frezeq0/bittrex-opensource

**Comment by muhammednagy** [comment]
seems like a wrong permissions

**Comment by frezeq00** [comment]
bittrex opensource: https://github.com/pkdcryptos/frezeq0_bittrex-opensource

**Comment by gejiajie** [comment]
Hi MuhammadNagy,
i see the doc about
     https://github.com/InfraexDev/peatio/blob/stable/doc/eth.md
what is the meaning about "don't forget to edit service.rb with your url"?  what is the url? could you give me a example?

**Comment by rraallvv** [comment]
@muhammednagy thanks for sharing the instructions for adding ETH.

I'm just curious, what does the filter service do, can't I just install the geth service?

Also, does geth.service daemonize the client too? Because, some scripts I've tried, for instance with the Bitcoin client, get stuck in the command line and never return to the command prompt without daemonization.

Keep up the good work.

**Comment by algobasket** [comment]
@rraallvv @gejiajie @sharmaabhishek2207 @skaleita 
Complete Peatio Help | Support | Bug Fixing
http://peatio.algobasket.com
Free Technical Documentation below :
https://github.com/peatio/peatio/files/2457278/PeatioCryptoExchange.pdf
https://www.youtube.com/watch?v=tpieNIMSBuQ
https://github.com/algobasket/PeatioCryptoExchange/
Contact me on Skype : algobasket
Thanks in advance !!!
