### ISSUE TITLE
Site not loading js or images

### ISSUE THREAD

**Issue by AELECTRIC** [peatio/peatio#700]
Hello, I seem to havean installation close to runing. he server starts up ok, however the website does not display images or load some pages. Some buttons and test show up but that is about it. The terminalrunning the server displays the following when the site is interacted with: 

> `ERROR: there is already one or more instance(s) of the program running
deploy@drupeone:~/peatio/peatio-master$ bundle exec rails server
=> Booting WEBrick
=> Rails 4.0.12 application starting in production on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
[2018-01-26 03:53:13] INFO  WEBrick 1.3.1
[2018-01-26 03:53:13] INFO  ruby 2.2.1 (2015-02-26) [x86_64-linux]
[2018-01-26 03:53:13] INFO  WEBrick::HTTPServer#start: pid=18433 port=3000
I, [2018-01-26T03:53:42.608952 #18433]  INFO -- : Started GET "/" for 127.0.0.1 at 2018-01-26 03:53:42 -0500
I, [2018-01-26T03:53:42.667533 #18433]  INFO -- : Processing by WelcomeController#index as HTML
I, [2018-01-26T03:53:42.707747 #18433]  INFO -- :   Rendered welcome/index.html.slim within layouts/landing (16.7ms)
I, [2018-01-26T03:53:42.721591 #18433]  INFO -- :   Rendered shared/_html5.html.slim (2.0ms)
I, [2018-01-26T03:53:42.726349 #18433]  INFO -- :   Rendered shared/_meta.html.slim (3.4ms)
I, [2018-01-26T03:53:42.747675 #18433]  INFO -- :   Rendered shared/_alert.html.slim (19.9ms)
I, [2018-01-26T03:53:42.768759 #18433]  INFO -- :   Rendered shared/_footer.html.slim (17.5ms)
I, [2018-01-26T03:53:42.769295 #18433]  INFO -- : Completed 200 OK in 101ms (Views: 85.0ms | ActiveRecord: 1.3ms)
I, [2018-01-26T03:53:42.839683 #18433]  INFO -- : Started GET "/stylesheets/application.css" for 127.0.0.1 at 2018-01-26 03:53:42 -0500
F, [2018-01-26T03:53:42.841267 #18433] FATAL -- : 
ActionController::RoutingError (No route matches [GET] "/stylesheets/application.css"):
  lib/middleware/security.rb:11:in `call'

I, [2018-01-26T03:53:42.847148 #18433]  INFO -- : Started GET "/javascripts/locales/en.js" for 127.0.0.1 at 2018-01-26 03:53:42 -0500
F, [2018-01-26T03:53:42.851145 #18433] FATAL -- : 
ActionController::RoutingError (No route matches [GET] "/javascripts/locales/en.js"):
  lib/middleware/security.rb:11:in `call'

I, [2018-01-26T03:53:42.856905 #18433]  INFO -- : Started GET "/javascripts/application.js" for 127.0.0.1 at 2018-01-26 03:53:42 -0500
F, [2018-01-26T03:53:42.858199 #18433] FATAL -- : 
ActionController::RoutingError (No route matches [GET] "/javascripts/application.js"):
  lib/middleware/security.rb:11:in `call'

I, [2018-01-26T03:53:42.860311 #18433]  INFO -- : Started GET "/images/logo.png" for 127.0.0.1 at 2018-01-26 03:53:42 -0500
F, [2018-01-26T03:53:42.862308 #18433] FATAL -- : 
ActionController::RoutingError (No route matches [GET] "/images/logo.png"):
  lib/middleware/security.rb:11:in `call'

I, [2018-01-26T03:53:42.864676 #18433]  INFO -- : Started GET "/javascripts/locales/en.js" for 127.0.0.1 at 2018-01-26 03:53:42 -0500
F, [2018-01-26T03:53:42.866018 #18433] FATAL -- : 
ActionController::RoutingError (No route matches [GET] "/javascripts/locales/en.js"):
  lib/middleware/security.rb:11:in `call'

I, [2018-01-26T03:53:42.910709 #18433]  INFO -- : Started GET "/images/logo.png" for 127.0.0.1 at 2018-01-26 03:53:42 -0500
F, [2018-01-26T03:53:42.914568 #18433] FATAL -- : 
ActionController::RoutingError (No route matches [GET] "/images/logo.png"):
  lib/middleware/security.rb:11:in `call'

I, [2018-01-26T03:53:51.514847 #18433]  INFO -- : Started GET "/signin" for 127.0.0.1 at 2018-01-26 03:53:51 -0500
I, [2018-01-26T03:53:51.519223 #18433]  INFO -- : Processing by SessionsController#new as HTML
I, [2018-01-26T03:53:51.584787 #18433]  INFO -- :   Rendered sessions/new.html.slim within layouts/application (30.7ms)
I, [2018-01-26T03:53:51.590919 #18433]  INFO -- :   Rendered shared/_html5.html.slim (0.1ms)
I, [2018-01-26T03:53:51.591871 #18433]  INFO -- :   Rendered shared/_meta.html.slim (0.5ms)
I, [2018-01-26T03:53:51.592411 #18433]  INFO -- :   Rendered shared/_alert.html.slim (0.2ms)
I, [2018-01-26T03:53:51.605287 #18433]  INFO -- :   Rendered shared/_header_lang_sel.html.slim (4.4ms)
I, [2018-01-26T03:53:51.605487 #18433]  INFO -- :   Rendered shared/_header.html.slim (11.6ms)
I, [2018-01-26T03:53:51.622204 #18433]  INFO -- :   Rendered shared/_flash.slim (11.3ms)
I, [2018-01-26T03:53:51.622434 #18433]  INFO -- :   Rendered shared/_frame.html.slim (15.7ms)
I, [2018-01-26T03:53:51.622671 #18433]  INFO -- :   Rendered shared/_footer.html.slim (0.0ms)
I, [2018-01-26T03:53:51.622922 #18433]  INFO -- : Completed 200 OK in 104ms (Views: 82.3ms | ActiveRecord: 5.2ms)
I, [2018-01-26T03:53:51.654926 #18433]  INFO -- : Started GET "/stylesheets/application.css" for 127.0.0.1 at 2018-01-26 03:53:51 -0500
F, [2018-01-26T03:53:51.656648 #18433] FATAL -- : 
ActionController::RoutingError (No route matches [GET] "/stylesheets/application.css"):
  lib/middleware/security.rb:11:in `call'

I, [2018-01-26T03:53:51.659970 #18433]  INFO -- : Started GET "/javascripts/application.js" for 127.0.0.1 at 2018-01-26 03:53:51 -0500
F, [2018-01-26T03:53:51.661593 #18433] FATAL -- : 
ActionController::RoutingError (No route matches [GET] "/javascripts/application.js"):
  lib/middleware/security.rb:11:in `call'

I, [2018-01-26T03:53:51.668178 #18433]  INFO -- : Started GET "/javascripts/locales/en.js" for 127.0.0.1 at 2018-01-26 03:53:51 -0500
F, [2018-01-26T03:53:51.675968 #18433] FATAL -- : 
ActionController::RoutingError (No route matches [GET] "/javascripts/locales/en.js"):
  lib/middleware/security.rb:11:in `call'

I, [2018-01-26T03:53:51.698062 #18433]  INFO -- : Started GET "/languages/en.png" for 127.0.0.1 at 2018-01-26 03:53:51 -0500
F, [2018-01-26T03:53:51.703095 #18433] FATAL -- : 
ActionController::RoutingError (No route matches [GET] "/languages/en.png"):
  lib/middleware/security.rb:11:in `call'

I, [2018-01-26T03:53:51.705143 #18433]  INFO -- : Started GET "/languages/zh-CN.png" for 127.0.0.1 at 2018-01-26 03:53:51 -0500
F, [2018-01-26T03:53:51.706717 #18433] FATAL -- : 
ActionController::RoutingError (No route matches [GET] "/languages/zh-CN.png"):
  lib/middleware/security.rb:11:in `call'

I, [2018-01-26T03:53:51.707464 #18433]  INFO -- : Started GET "/languages/ko.png" for 127.0.0.1 at 2018-01-26 03:53:51 -0500
F, [2018-01-26T03:53:51.708611 #18433] FATAL -- : 
ActionController::RoutingError (No route matches [GET] "/languages/ko.png"):
  lib/middleware/security.rb:11:in `call'

I, [2018-01-26T03:53:57.348888 #18433]  INFO -- : Started POST "/auth/identity/callback" for 127.0.0.1 at 2018-01-26 03:53:57 -0500
I, [2018-01-26T03:53:57.349383 #18433]  INFO -- : (identity) Callback phase initiated.
E, [2018-01-26T03:53:57.351857 #18433] ERROR -- : (identity) Authentication failure! invalid_credentials encountered.
I, [2018-01-26T03:53:57.355084 #18433]  INFO -- : Processing by SessionsController#failure as HTML
I, [2018-01-26T03:53:57.355183 #18433]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"O8YqxUvKKQMVVYYTBlpf0i8PIJluABAKfmbHspFGGrU=", "auth_key"=>"boldt.brad@gmail.com", "password"=>"[FILTERED]", "commit"=>"Sign In"}
I, [2018-01-26T03:53:57.366424 #18433]  INFO -- : Redirected to http://localhost:3000/signin
I, [2018-01-26T03:53:57.366593 #18433]  INFO -- : Completed 302 Found in 11ms (ActiveRecord: 3.1ms)
I, [2018-01-26T03:53:57.379854 #18433]  INFO -- : Started GET "/signin" for 127.0.0.1 at 2018-01-26 03:53:57 -0500
I, [2018-01-26T03:53:57.380887 #18433]  INFO -- : Processing by SessionsController#new as HTML
I, [2018-01-26T03:53:57.391321 #18433]  INFO -- :   Rendered sessions/new.html.slim within layouts/application (3.7ms)
I, [2018-01-26T03:53:57.393831 #18433]  INFO -- :   Rendered shared/_html5.html.slim (0.1ms)
I, [2018-01-26T03:53:57.394393 #18433]  INFO -- :   Rendered shared/_meta.html.slim (0.4ms)
I, [2018-01-26T03:53:57.395085 #18433]  INFO -- :   Rendered shared/_alert.html.slim (0.3ms)
I, [2018-01-26T03:53:57.399068 #18433]  INFO -- :   Rendered shared/_header_lang_sel.html.slim (0.1ms)
I, [2018-01-26T03:53:57.399250 #18433]  INFO -- :   Rendered shared/_header.html.slim (3.9ms)
I, [2018-01-26T03:53:57.399961 #18433]  INFO -- :   Rendered shared/_flash.slim (0.1ms)
I, [2018-01-26T03:53:57.400076 #18433]  INFO -- :   Rendered shared/_frame.html.slim (0.7ms)
I, [2018-01-26T03:53:57.400255 #18433]  INFO -- :   Rendered shared/_footer.html.slim (0.0ms)
I, [2018-01-26T03:53:57.400459 #18433]  INFO -- : Completed 200 OK in 19ms (Views: 13.3ms | ActiveRecord: 0.2ms)
I, [2018-01-26T03:53:57.469904 #18433]  INFO -- : Started GET "/stylesheets/application.css" for 127.0.0.1 at 2018-01-26 03:53:57 -0500
F, [2018-01-26T03:53:57.474537 #18433] FATAL -- : 
ActionController::RoutingError (No route matches [GET] "/stylesheets/application.css"):
  lib/middleware/security.rb:11:in `call'

I, [2018-01-26T03:53:57.475608 #18433]  INFO -- : Started GET "/javascripts/locales/en.js" for 127.0.0.1 at 2018-01-26 03:53:57 -0500
F, [2018-01-26T03:53:57.477296 #18433] FATAL -- : 
ActionController::RoutingError (No route matches [GET] "/javascripts/locales/en.js"):
  lib/middleware/security.rb:11:in `call'

I, [2018-01-26T03:53:57.478086 #18433]  INFO -- : Started GET "/javascripts/application.js" for 127.0.0.1 at 2018-01-26 03:53:57 -0500
F, [2018-01-26T03:53:57.479412 #18433] FATAL -- : 
ActionController::RoutingError (No route matches [GET] "/javascripts/application.js"):
  lib/middleware/security.rb:11:in `call'

I, [2018-01-26T03:53:57.486378 #18433]  INFO -- : Started GET "/javascripts/locales/en.js" for 127.0.0.1 at 2018-01-26 03:53:57 -0500
F, [2018-01-26T03:53:57.489156 #18433] FATAL -- : 
ActionController::RoutingError (No route matches [GET] "/javascripts/locales/en.js"):
  lib/middleware/security.rb:11:in `call'

I, [2018-01-26T03:53:57.514339 #18433]  INFO -- : Started GET "/languages/en.png" for 127.0.0.1 at 2018-01-26 03:53:57 -0500
F, [2018-01-26T03:53:57.516892 #18433] FATAL -- : 
ActionController::RoutingError (No route matches [GET] "/languages/en.png"):
  lib/middleware/security.rb:11:in `call'

I, [2018-01-26T03:53:57.519071 #18433]  INFO -- : Started GET "/languages/ko.png" for 127.0.0.1 at 2018-01-26 03:53:57 -0500
F, [2018-01-26T03:53:57.521682 #18433] FATAL -- : 
ActionController::RoutingError (No route matches [GET] "/languages/ko.png"):
  lib/middleware/security.rb:11:in `call'

I, [2018-01-26T03:53:57.522213 #18433]  INFO -- : Started GET "/languages/zh-CN.png" for 127.0.0.1 at 2018-01-26 03:53:57 -0500
F, [2018-01-26T03:53:57.524127 #18433] FATAL -- : 
ActionController::RoutingError (No route matches [GET] "/languages/zh-CN.png"):
  lib/middleware/security.rb:11:in `call'

>

**Comment by mrkurosawa** [comment]
You must start server in development mode or install peatio by guide https://github.com/peatio/peatio/blob/master/doc/deploy-production-server.md

**Comment by onlyyouandty** [comment]
It sounds like an assets issue. Try to to run these commands.
```
bundle exec rake assets:clean
bundle exec rake assets:clobber
bundle exec rake tmp:clear
bundle exec rake assets:precompile
```

**Comment by peatioMan** [comment]
HI can help you. 

Add me on skype, just search Peatio Man or add by id:
cid-(-8618737192104534817)@outlook.com

**Comment by algobasket** [comment]
@AELECTRIC 
Complete Peatio Help | Support | Bug Fixing
http://peatio.algobasket.com
Free Technical Documentation below :
https://github.com/peatio/peatio/files/2457278/PeatioCryptoExchange.pdf
https://www.youtube.com/watch?v=tpieNIMSBuQ
https://github.com/algobasket/PeatioCryptoExchange/
Contact me on Skype : algobasket
Thanks in advance !!!
