### ISSUE TITLE
MarketsController#show wrong argument type nil

### ISSUE THREAD

**Issue by chasel** [peatio/peatio#701]
```
Started GET "/markets/btccny" for 127.0.0.1 at 2018-01-29 12:44:28 +0800
Processing by Private::MarketsController#show as HTML
  Parameters: {"id"=>"btccny", "market"=>"btccny", "ask"=>"btc", "bid"=>"cny"}
  [1m[36mMember Load (0.3ms)[0m  [1mSELECT `members`.* FROM `members` WHERE `members`.`disabled` = 0 AND `members`.`id` = 1 ORDER BY `members`.`id` ASC LIMIT 1[0m
  [1m[35mAccount Load (0.3ms)[0m  SELECT `accounts`.* FROM `accounts` WHERE `accounts`.`member_id` = 1
Completed 500 Internal Server Error in 134351ms

TypeError - wrong argument type nil (expected Symbol):
  activerecord (4.0.13) lib/active_record/relation/delegation.rb:20:in `block in <module:ClassSpecificRelation>'
  activesupport (4.0.13) lib/active_support/concern.rb:114:in `append_features'
  activerecord-deprecated_finders (1.0.4) lib/active_record/deprecated_finders/collection_proxy.rb:30:in `block in inherited'
  activerecord-deprecated_finders (1.0.4) lib/active_record/deprecated_finders/collection_proxy.rb:28:in `inherited'
  activerecord (4.0.13) lib/active_record/relation/delegation.rb:85:in `const_missing'
  activerecord (4.0.13) lib/active_record/relation/delegation.rb:97:in `block in relation_class_for'
  thread_safe (0.3.6) lib/thread_safe/non_concurrent_cache_backend.rb:23:in `compute_if_absent'
  thread_safe (0.3.6) lib/thread_safe/mri_cache_backend.rb:20:in `block in compute_if_absent'
  thread_safe (0.3.6) lib/thread_safe/mri_cache_backend.rb:20:in `compute_if_absent'
  activerecord (4.0.13) lib/active_record/relation/delegation.rb:95:in `relation_class_for'
  activerecord (4.0.13) lib/active_record/relation/delegation.rb:77:in `new'
  activerecord (4.0.13) lib/active_record/associations/collection_association.rb:42:in `reader'
  activerecord (4.0.13) lib/active_record/associations/builder/association.rb:70:in `orders'
  app/controllers/private/markets_controller.rb:42:in `set_member_data'
  app/controllers/private/markets_controller.rb:26:in `show'
  actionpack (4.0.13) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.0.13) lib/abstract_controller/base.rb:189:in `process_action'
  actionpack (4.0.13) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.0.13) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  activesupport (4.0.13) lib/active_support/callbacks.rb:483:in `_run__4574981545427177940__process_action__callbacks'
  activesupport (4.0.13) lib/active_support/callbacks.rb:80:in `run_callbacks'
  actionpack (4.0.13) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (4.0.13) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.0.13) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  activesupport (4.0.13) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.0.13) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.0.13) lib/active_support/notifications.rb:159:in `instrument'
  actionpack (4.0.13) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.0.13) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.0.13) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.0.13) lib/abstract_controller/base.rb:136:in `process'
  actionpack (4.0.13) lib/abstract_controller/rendering.rb:44:in `process'
  actionpack (4.0.13) lib/action_controller/metal.rb:195:in `dispatch'
  actionpack (4.0.13) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.0.13) lib/action_controller/metal.rb:231:in `block in action'
  actionpack (4.0.13) lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
  actionpack (4.0.13) lib/action_dispatch/routing/route_set.rb:50:in `call'
  actionpack (4.0.13) lib/action_dispatch/routing/mapper.rb:44:in `call'
  actionpack (4.0.13) lib/action_dispatch/journey/router.rb:71:in `block in call'
  actionpack (4.0.13) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.0.13) lib/action_dispatch/routing/route_set.rb:676:in `call'
  omniauth (1.2.2) lib/omniauth/strategy.rb:186:in `call!'
  omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
  omniauth (1.2.2) lib/omniauth/strategy.rb:404:in `call_app!'
  omniauth-identity (1.1.1) lib/omniauth/strategies/identity.rb:43:in `other_phase'
  omniauth (1.2.2) lib/omniauth/strategy.rb:185:in `call!'
  omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
  omniauth (1.2.2) lib/omniauth/builder.rb:59:in `call'
  meta_request (0.2.9) lib/meta_request/middlewares/app_request_handler.rb:13:in `call'
  rack-contrib (1.8.0) lib/rack/contrib/response_headers.rb:17:in `call'
  meta_request (0.2.9) lib/meta_request/middlewares/headers.rb:16:in `call'
  meta_request (0.2.9) lib/meta_request/middlewares/meta_request_handler.rb:13:in `call'
  http_accept_language (2.0.5) lib/http_accept_language/middleware.rb:14:in `call'
  simple_captcha2 (0.2.2) lib/simple_captcha/middleware.rb:20:in `call'
  rack (1.5.5) lib/rack/etag.rb:23:in `call'
  rack (1.5.5) lib/rack/conditionalget.rb:25:in `call'
  rack (1.5.5) lib/rack/head.rb:11:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/flash.rb:241:in `call'
  rack (1.5.5) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.5.5) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/cookies.rb:486:in `call'
  activerecord (4.0.13) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.0.13) lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in `call'
  activerecord (4.0.13) lib/active_record/migration.rb:373:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.0.13) lib/active_support/callbacks.rb:373:in `_run__2047302180822707128__call__callbacks'
  activesupport (4.0.13) lib/active_support/callbacks.rb:80:in `run_callbacks'
  actionpack (4.0.13) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/reloader.rb:64:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  better_errors (1.1.0) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (1.1.0) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (1.1.0) lib/better_errors/middleware.rb:56:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.0.13) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.0.13) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.0.13) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.0.13) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.0.13) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.0.13) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.0.3) lib/quiet_assets.rb:23:in `call_with_quiet_assets'
  request_store (1.4.0) lib/request_store/middleware.rb:19:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.5) lib/rack/runtime.rb:17:in `call'
  lib/middleware/security.rb:11:in `call'
  rack (1.5.5) lib/rack/lock.rb:17:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/static.rb:84:in `call'
  lib/middleware/i18n_js.rb:9:in `call'
  rack (1.5.5) lib/rack/sendfile.rb:112:in `call'
  railties (4.0.13) lib/rails/engine.rb:511:in `call'
  railties (4.0.13) lib/rails/application.rb:97:in `call'
  rack (1.5.5) lib/rack/lock.rb:17:in `call'
  rack (1.5.5) lib/rack/content_length.rb:14:in `call'
  rack (1.5.5) lib/rack/handler/webrick.rb:60:in `service'
```
how to solve the error?

**Comment by scatterp** [comment]
fix the symbol section of your currency.yml
