### ISSUE TITLE
Peatio not loading Images and html Pages like Deposite for Funds etc

### ISSUE THREAD

**Issue by kashifasif** [peatio/peatio#706]
Hi!,installation done successfully and server is running good., but the website does not display images and some pages. Terminal Show
I, [2018-02-02T12:46:40.934231 #3300]  INFO -- :   Rendered shared/_header.html.slim (1.8ms)
I, [2018-02-02T12:46:40.934526 #3300]  INFO -- :   Rendered shared/_flash.slim (0.0ms)
I, [2018-02-02T12:46:40.934579 #3300]  INFO -- :   Rendered shared/_frame.html.slim (0.3ms)
I, [2018-02-02T12:46:40.934660 #3300]  INFO -- :   Rendered shared/_footer.html.slim (0.0ms)
I, [2018-02-02T12:46:40.934764 #3300]  INFO -- : Completed 200 OK in 16ms (Views: 8.3ms | ActiveRecord: 1.7ms)
I, [2018-02-02T12:46:41.272127 #3300]  INFO -- : Started GET "/languages/en.png" for 182.191.121.157 at 2018-02-02 12:46:41 +0100
F, [2018-02-02T12:46:41.275559 #3300] FATAL -- :
ActionController::RoutingError (No route matches [GET] "/languages/en.png"):
  lib/middleware/security.rb:11:in `call'

I, [2018-02-02T12:46:41.388903 #3300]  INFO -- : Started GET "/languages/zh-CN.png" for 182.191.121.157 at 2018-02-02 12:46:41 +0100
F, [2018-02-02T12:46:41.390414 #3300] FATAL -- :
ActionController::RoutingError (No route matches [GET] "/languages/zh-CN.png"):
  lib/middleware/security.rb:11:in `call'

I, [2018-02-02T12:46:41.549759 #3300]  INFO -- : Started GET "/languages/ko.png" for 182.191.121.157 at 2018-02-02 12:46:41 +0100
F, [2018-02-02T12:46:41.551370 #3300] FATAL -- :
ActionController::RoutingError (No route matches [GET] "/languages/ko.png"):
  lib/middleware/security.rb:11:in `call'
![peatio-screen](https://user-images.githubusercontent.com/8712630/35732024-b0513f8e-0839-11e8-93e6-1c5397de04f8.JPG)

**Comment by scatterp** [comment]
not sure which version you used here of peatio you can use mine to fix this github.com/scatterp/peatio to avoid such errors if your still stuck hit me up on skype simon.m.day

**Comment by rbgtbusiness** [comment]
Solved ?

**Comment by frezeq0** [comment]
bittrex opensource: https://github.com/frezeq0/bittrex-opensource

**Comment by algobasket** [comment]
@kashifasif 
Complete Peatio Help | Support | Bug Fixing
http://peatio.algobasket.com
Free Technical Documentation below :
https://github.com/peatio/peatio/files/2457278/PeatioCryptoExchange.pdf
https://www.youtube.com/watch?v=tpieNIMSBuQ
https://github.com/algobasket/PeatioCryptoExchange/
Contact me on Skype : algobasket
Thanks in advance !!!
