### ISSUE TITLE
Circular dependency detected while autoloading constant PaymentTransaction (RuntimeError)

### ISSUE THREAD

**Issue by anibha88** [peatio/peatio#710]
Hi everyone,
I was trying to get this run on AWS. I followed all the instructions as per:
https://github.com/peatio/peatio/blob/master/doc/deploy-production-server.md

But I am stuck with this error. Any advise or guidance would be greatly appreciated..!!

Below is the log trace when I try to run the rails server

/home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:461:in `load_missing_constant': Circular dependency detected while autoloading constant PaymentTransaction (RuntimeError)
	from /home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:184:in `const_missing'
	from /home/ubuntu/peatio/current/lib/daemons/payment_transaction.rb:20:in `<top (required)>'
	from /home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:229:in `require'
	from /home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:229:in `block in require'
	from /home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:214:in `load_dependency'
	from /home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:229:in `require'
	from /home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:330:in `require_or_load'
	from /home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:289:in `depend_on'
	from /home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:207:in `require_dependency'
	from /home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/engine.rb:465:in `block (2 levels) in eager_load!'
	from /home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/engine.rb:464:in `each'
	from /home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/engine.rb:464:in `block in eager_load!'
	from /home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/engine.rb:462:in `each'
	from /home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/engine.rb:462:in `eager_load!'
	from /home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/engine.rb:347:in `eager_load!'
	from /home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/application/finisher.rb:56:in `each'
	from /home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/application/finisher.rb:56:in `block in <module:Finisher>'
	from /home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/initializable.rb:30:in `run'
	from /home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/initializable.rb:54:in `run_initializers'
	from /home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/application.rb:215:in `initialize!'
	from /home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/railtie/configurable.rb:30:in `method_missing'
	from /home/ubuntu/peatio/current/config/environment.rb:5:in `<top (required)>'
	from /home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:229:in `require'
	from /home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:229:in `block in require'
	from /home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:214:in `load_dependency'
	from /home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:229:in `require'
	from /home/ubuntu/peatio/current/config.ru:3:in `block in <main>'
	from /home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
	from /home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
	from /home/ubuntu/peatio/current/config.ru:in `new'
	from /home/ubuntu/peatio/current/config.ru:in `<main>'
	from /home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/builder.rb:49:in `eval'
	from /home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/builder.rb:49:in `new_from_string'
	from /home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/builder.rb:40:in `parse_file'
	from /home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/server.rb:277:in `build_app_and_options_from_config'
	from /home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/server.rb:199:in `app'
	from /home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/commands/server.rb:48:in `app'
	from /home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/server.rb:314:in `wrapped_app'
	from /home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/commands/server.rb:75:in `start'
	from /home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/commands.rb:76:in `block in <top (required)>'
	from /home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/commands.rb:71:in `tap'
	from /home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/commands.rb:71:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'

**Comment by anibha88** [comment]
Hi @muhammednagy 
Thank you very much! I ll fork from here. I am a newbie to this... In case if I face some issues, I ll put it up. Please help!
Thanks :)
