### ISSUE TITLE
Redis::CommandError (NOAUTH Authentication required.)

### ISSUE THREAD

**Issue by dragon28** [peatio/peatio#821]
Hello People :)

Error Log:

```
~/peatio$ bundle exec rails server -p 3000
/home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. false was converted to "false". (StructuredWarnings::StandardWarning)=> Booting Puma
=> Rails 4.2.10 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Puma starting in single mode...
* Version 3.11.4 (ruby 2.5.3-p105), codename: Love Song
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://localhost:3000
Use Ctrl-C to stop


Started GET "/" for 127.0.0.1 at 2018-11-21 18:51:41 +0800
  ActiveRecord::SchemaMigration Load (0.5ms)  SELECT `schema_migrations`.* FROM `schema_migrations`
Processing by WelcomeController#index as HTML
  Market Load (5.1ms)  SELECT  `markets`.* FROM `markets` WHERE `markets`.`enabled` = 1  ORDER BY `markets`.`position` ASC LIMIT 1
Completed 500 Internal Server Error in 116ms (ActiveRecord: 24.5ms)

Redis::CommandError (NOAUTH Authentication required.):
  app/trading/global.rb:45:in `ticker'
  app/models/market.rb:88:in `ticker'
  app/controllers/application_controller.rb:51:in `set_gon'


  Rendered /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/_source.erb (19.8ms)
  Rendered /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (7.8ms)
  Rendered /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.1ms)
  Rendered /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (72.3ms)


Started GET "/" for 127.0.0.1 at 2018-11-21 18:51:47 +0800
Processing by WelcomeController#index as HTML
  Market Load (0.9ms)  SELECT  `markets`.* FROM `markets` WHERE `markets`.`enabled` = 1  ORDER BY `markets`.`position` ASC LIMIT 1
Completed 500 Internal Server Error in 3ms (ActiveRecord: 0.9ms)

Redis::CommandError (NOAUTH Authentication required.):
  app/trading/global.rb:45:in `ticker'
  app/models/market.rb:88:in `ticker'
  app/controllers/application_controller.rb:51:in `set_gon'


  Rendered /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/_source.erb (5.9ms)
  Rendered /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (3.5ms)
  Rendered /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.0ms)
  Rendered /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (28.2ms)


Started GET "/" for 127.0.0.1 at 2018-11-21 18:56:39 +0800
Processing by WelcomeController#index as HTML
  Market Load (8.1ms)  SELECT  `markets`.* FROM `markets` WHERE `markets`.`enabled` = 1  ORDER BY `markets`.`position` ASC LIMIT 1
Completed 500 Internal Server Error in 25ms (ActiveRecord: 8.1ms)

Redis::CommandError (NOAUTH Authentication required.):
  app/trading/global.rb:45:in `ticker'
  app/models/market.rb:88:in `ticker'
  app/controllers/application_controller.rb:51:in `set_gon'


  Rendered /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/_source.erb (5.4ms)
  Rendered /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (13.3ms)
  Rendered /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.9ms)
  Rendered /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (100.2ms)


Started GET "/" for 127.0.0.1 at 2018-11-21 18:56:42 +0800
Processing by WelcomeController#index as HTML
  Market Load (7.1ms)  SELECT  `markets`.* FROM `markets` WHERE `markets`.`enabled` = 1  ORDER BY `markets`.`position` ASC LIMIT 1
Completed 500 Internal Server Error in 12ms (ActiveRecord: 7.1ms)

Redis::CommandError (NOAUTH Authentication required.):
  app/trading/global.rb:45:in `ticker'
  app/models/market.rb:88:in `ticker'
  app/controllers/application_controller.rb:51:in `set_gon'


  Rendered /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/_source.erb (12.4ms)
  Rendered /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (2.1ms)
  Rendered /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.9ms)
  Rendered /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (71.7ms)


Started GET "/" for 127.0.0.1 at 2018-11-21 18:56:51 +0800
Processing by WelcomeController#index as HTML
  Market Load (8.4ms)  SELECT  `markets`.* FROM `markets` WHERE `markets`.`enabled` = 1  ORDER BY `markets`.`position` ASC LIMIT 1
Completed 500 Internal Server Error in 13ms (ActiveRecord: 8.4ms)

Redis::CommandError (NOAUTH Authentication required.):
  app/trading/global.rb:45:in `ticker'
  app/models/market.rb:88:in `ticker'
  app/controllers/application_controller.rb:51:in `set_gon'


  Rendered /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/_source.erb (40.0ms)
  Rendered /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (14.6ms)
  Rendered /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.1ms)
  Rendered /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (107.6ms)


Started GET "/" for 127.0.0.1 at 2018-11-21 18:57:05 +0800
Processing by WelcomeController#index as HTML
  Market Load (0.6ms)  SELECT  `markets`.* FROM `markets` WHERE `markets`.`enabled` = 1  ORDER BY `markets`.`position` ASC LIMIT 1
Completed 500 Internal Server Error in 9ms (ActiveRecord: 0.6ms)

Redis::CommandError (NOAUTH Authentication required.):
  app/trading/global.rb:45:in `ticker'
  app/models/market.rb:88:in `ticker'
  app/controllers/application_controller.rb:51:in `set_gon'


  Rendered /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/_source.erb (5.3ms)
  Rendered /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (2.5ms)
  Rendered /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.0ms)
  Rendered /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (27.2ms)
^C- Gracefully stopping, waiting for requests to finish
=== puma shutdown: 2018-11-21 18:57:46 ===
- Goodbye!
Exiting
```
application.yml

```
~/peatio$ cat config/application.yml | grep REDIS

  #REDIS_URL:      redis://localhost:6379
  REDIS_URL:      redis://127.0.0.1:6379
  REDIS_PASSWORD:	qeEx
  #REDIS_PASSWORD: ~ # By default no password is sent to Redis server. Change this if you want to connect using password.
```

I am not sure what cause the Redis::CommandError (NOAUTH Authentication required.) because I have set the application.yml.

Thanks

**Comment by dragon28** [comment]
Hello People :)

Additional details:

```
redis (4.0.2) lib/redis/client.rb:119:in `call'
redis (4.0.2) lib/redis.rb:899:in `block in get'
redis (4.0.2) lib/redis.rb:45:in `block in synchronize'
/home/dragon/.rbenv/versions/2.5.3/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
redis (4.0.2) lib/redis.rb:45:in `synchronize'
redis (4.0.2) lib/redis.rb:898:in `get'
redis-store (1.6.0) lib/redis/store/interface.rb:5:in `get'
redis-store (1.6.0) lib/redis/store/serialization.rb:17:in `get'
redis-store (1.6.0) lib/redis/store/namespace.rb:23:in `block in get'
redis-store (1.6.0) lib/redis/store/namespace.rb:89:in `namespace'
redis-store (1.6.0) lib/redis/store/namespace.rb:23:in `get'
redis-activesupport (5.0.7) lib/active_support/cache/redis_store.rb:266:in `block in read_entry'
redis-activesupport (5.0.7) lib/active_support/cache/redis_store.rb:248:in `with'
redis-activesupport (5.0.7) lib/active_support/cache/redis_store.rb:266:in `read_entry'
activesupport (4.2.10) lib/active_support/cache.rb:315:in `block in read'
activesupport (4.2.10) lib/active_support/cache.rb:547:in `block in instrument'
activesupport (4.2.10) lib/active_support/notifications.rb:166:in `instrument'
activesupport (4.2.10) lib/active_support/cache.rb:547:in `instrument'
activesupport (4.2.10) lib/active_support/cache.rb:314:in `read'
app/trading/global.rb:45:in `ticker'
app/models/market.rb:88:in `ticker'
app/controllers/application_controller.rb:51:in `set_gon'
activesupport (4.2.10) lib/active_support/callbacks.rb:432:in `block in make_lambda'
activesupport (4.2.10) lib/active_support/callbacks.rb:164:in `block in halting'
activesupport (4.2.10) lib/active_support/callbacks.rb:504:in `block in call'
activesupport (4.2.10) lib/active_support/callbacks.rb:504:in `each'
activesupport (4.2.10) lib/active_support/callbacks.rb:504:in `call'
activesupport (4.2.10) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
activesupport (4.2.10) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
activesupport (4.2.10) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.10) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.2.10) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.2.10) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (4.2.10) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.10) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.10) lib/active_support/notifications.rb:164:in `instrument'
actionpack (4.2.10) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.2.10) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.2.10) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.2.10) lib/abstract_controller/base.rb:137:in `process'
actionview (4.2.10) lib/action_view/rendering.rb:30:in `process'
actionpack (4.2.10) lib/action_controller/metal.rb:196:in `dispatch'
actionpack (4.2.10) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.2.10) lib/action_controller/metal.rb:237:in `block in action'
actionpack (4.2.10) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
actionpack (4.2.10) lib/action_dispatch/routing/route_set.rb:43:in `serve'
actionpack (4.2.10) lib/action_dispatch/journey/router.rb:43:in `block in serve'
actionpack (4.2.10) lib/action_dispatch/journey/router.rb:30:in `each'
actionpack (4.2.10) lib/action_dispatch/journey/router.rb:30:in `serve'
actionpack (4.2.10) lib/action_dispatch/routing/route_set.rb:817:in `call'
omniauth (1.8.1) lib/omniauth/strategy.rb:190:in `call!'
omniauth (1.8.1) lib/omniauth/strategy.rb:168:in `call'
omniauth (1.8.1) lib/omniauth/builder.rb:63:in `call'
bullet (5.7.6) lib/bullet/rack.rb:12:in `call'
rack (1.6.11) lib/rack/etag.rb:24:in `call'
rack (1.6.11) lib/rack/conditionalget.rb:25:in `call'
rack (1.6.11) lib/rack/head.rb:13:in `call'
actionpack (4.2.10) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.2.10) lib/action_dispatch/middleware/flash.rb:260:in `call'
rack (1.6.11) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.6.11) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.2.10) lib/action_dispatch/middleware/cookies.rb:560:in `call'
activerecord (4.2.10) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.2.10) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
activerecord (4.2.10) lib/active_record/migration.rb:377:in `call'
actionpack (4.2.10) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.2.10) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
activesupport (4.2.10) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
activesupport (4.2.10) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.10) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.2.10) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.2.10) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
actionpack (4.2.10) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.2.10) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.2.10) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.10) lib/rails/rack/logger.rb:22:in `call'
quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
request_store (1.4.1) lib/request_store/middleware.rb:19:in `call'
actionpack (4.2.10) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.6.11) lib/rack/methodoverride.rb:22:in `call'
rack (1.6.11) lib/rack/runtime.rb:18:in `call'
rack (1.6.11) lib/rack/lock.rb:17:in `call'
actionpack (4.2.10) lib/action_dispatch/middleware/static.rb:120:in `call'
rack (1.6.11) lib/rack/sendfile.rb:113:in `call'
railties (4.2.10) lib/rails/engine.rb:518:in `call'
railties (4.2.10) lib/rails/application.rb:165:in `call'
rack (1.6.11) lib/rack/content_length.rb:15:in `call'
puma (3.11.4) lib/puma/configuration.rb:225:in `call'
puma (3.11.4) lib/puma/server.rb:632:in `handle_request'
puma (3.11.4) lib/puma/server.rb:446:in `process_client'
puma (3.11.4) lib/puma/server.rb:306:in `block in run'
puma (3.11.4) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```
